/* Field Sketch v2 — job storage, locked snaps, SLD99 DXF, KML and area split tools */
const PERCH_M2=25.29285264,ROOD=40,ACRE=160;
const JOBS_KEY='fieldsketch_jobs_v2',LAST_JOB_KEY='fieldsketch_last_job_v2';
const SLD99_DEF='+proj=tmerc +lat_0=7.00047152777778 +lon_0=80.7717130833333 +k=0.9999238418 +x_0=500000 +y_0=500000 +ellps=evrst30 +towgs84=-0.293,766.95,87.713,-0.195704,-1.695068,-3.473016,-0.039338 +units=m +no_defs +type=crs';
if(window.proj4) proj4.defs('EPSG:5235',SLD99_DEF);

function arpToM2(a,r,p){return(a*ACRE+r*ROOD+p)*PERCH_M2}
function m2ToARP(m2){let p=m2/PERCH_M2,a=Math.floor(p/ACRE);p-=a*ACRE;let r=Math.floor(p/ROOD);p-=r*ROOD;return{A:a,R:r,P:p}}
function arpText(m2){const o=m2ToARP(m2);return`${o.A}A ${o.R}R ${o.P.toFixed(2)}P`}
function ringAreaM2(ll){if(ll.length<3)return 0;const R=6378137;let s=0;for(let i=0;i<ll.length;i++){const a=ll[i],b=ll[(i+1)%ll.length];s+=(b.lng-a.lng)*Math.PI/180*(2+Math.sin(a.lat*Math.PI/180)+Math.sin(b.lat*Math.PI/180))}return Math.abs(s*R*R/2)}
function centroid(ll){let x=0,y=0,z=0;ll.forEach(p=>{const la=p.lat*Math.PI/180,lo=p.lng*Math.PI/180;x+=Math.cos(la)*Math.cos(lo);y+=Math.cos(la)*Math.sin(lo);z+=Math.sin(la)});return L.latLng(Math.atan2(z,Math.hypot(x,y))*180/Math.PI,Math.atan2(y,x)*180/Math.PI)}
function htmlEsc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function xmlEsc(s){return String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function downloadText(text,name,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
function toSLD(ll){if(!window.proj4)throw Error('Coordinate converter did not load');return proj4('EPSG:4326','EPSG:5235',[ll.lng,ll.lat])}
function fromSLD(e,n){if(!window.proj4)throw Error('Coordinate converter did not load');const q=proj4('EPSG:5235','EPSG:4326',[e,n]);return L.latLng(q[1],q[0])}

function startApp(){
  const map=L.map('map',{zoomControl:false,attributionControl:false,tap:false}).setView([7.1731,80.3050],16);
  const googleHyb=L.tileLayer('https://mt{s}.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',{subdomains:['0','1','2','3'],maxZoom:21,maxNativeZoom:21});
  const esriSat=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:21,maxNativeZoom:19});
  const WAYBACK={'2024':64776,'2023':1105,'2022':11475,'2021':10,'2020':17162,'2019':13882,'2018':7014,'2017':16681,'2016':10788,'2014':10};
  const waybackLayer=r=>L.tileLayer(`https://wayback.maptiles.arcgis.com/arcgis/rest/services/World_Imagery/MapServer/tile/${r}/{z}/{y}/{x}`,{maxZoom:21,maxNativeZoom:19});
  let current=googleHyb.addTo(map);const setBase=l=>{if(current)map.removeLayer(current);current=l.addTo(map);current.bringToBack()};
  const yearSel=document.getElementById('yearSel');yearSel.innerHTML='<option value="google">Google (latest)</option><option value="esri">Esri (latest)</option>'+Object.keys(WAYBACK).sort((a,b)=>b-a).map(y=>`<option value="wb${y}">📅 ${y}</option>`).join('');
  yearSel.onchange=()=>{const v=yearSel.value;if(v==='google')setBase(googleHyb);else if(v==='esri')setBase(esriSat);else{setBase(waybackLayer(WAYBACK[v.slice(2)]));toast('Imagery: '+v.slice(2))}};
  let gErr=0;googleHyb.on('tileerror',()=>{if(++gErr===6){yearSel.value='esri';setBase(esriSat);toast('Google tiles blocked — Esri loaded')}});

  let mode='pan',pts=[],pointMeta=[],locks=[],markers=[],poly=null,labelMarker=null,fitted=false,savedLands=[],referenceRings=[],referenceLayers=[];
  let snapOn=true,currentJobId='',pickMode='',pickPts=[],cutLayer=null,walkWatch=null,lastGps=null;
  const SNAP_PX=18,modeSeg=document.getElementById('modeSeg');
  let toastTimer=null;function toast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)} window._toast=toast;
  const hint=m=>document.getElementById('hint').innerHTML=m;
  const targetM2=()=>arpToM2(+document.getElementById('A').value||0,+document.getElementById('R').value||0,+document.getElementById('P').value||0);
  const nextMeta=()=>({no:document.getElementById('pointNo').value.trim()||String(pts.length+1),code:document.getElementById('pointCode').value.trim()});

  modeSeg.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;mode=b.dataset.m;pickMode='';pickPts=[];clearCut();[...modeSeg.children].forEach(x=>x.classList.toggle('on',x===b));map.dragging.enable();hint(mode==='draw'?'ඉඩම වටේ tap කරන්න. Red points are locked snapped vertices.':mode==='insert'?'Current edge එක මත tap කර point එකක් insert කරන්න.':'Map pan/zoom mode.')});

  function allSnapRings(){return savedLands.map(x=>x.pts).concat(referenceRings)}
  function snapPoint(latlng){if(!snapOn)return{ll:latlng,snapped:false};const cp=map.latLngToContainerPoint(latlng);let best=null,bestd=SNAP_PX;for(const ring of allSnapRings())for(const v of ring){const p=map.latLngToContainerPoint(v),d=Math.hypot(p.x-cp.x,p.y-cp.y);if(d<bestd){bestd=d;best=v}}if(best)return{ll:L.latLng(best.lat,best.lng),snapped:true};bestd=SNAP_PX;for(const ring of allSnapRings()){for(let i=0;i<ring.length;i++){const a=map.latLngToContainerPoint(ring[i]),b=map.latLngToContainerPoint(ring[(i+1)%ring.length]),dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((cp.x-a.x)*dx+(cp.y-a.y)*dy)/l2)),x=a.x+dx*t,y=a.y+dy*t,d=Math.hypot(x-cp.x,y-cp.y);if(d<bestd){bestd=d;best=map.containerPointToLatLng(L.point(x,y))}}}return best?{ll:best,snapped:true}:{ll:latlng,snapped:false}}
  function makeMarker(ll,i){const locked=!!locks[i],m=L.marker(ll,{icon:L.divIcon({className:'',html:`<div class="mk ${locked?'locked-dot':''}"></div>`,iconSize:[14,14],iconAnchor:[7,7]}),draggable:true});m.on('drag',ev=>{const j=markers.indexOf(m);pts[j]=ev.latlng;locks[j]=false;redraw()});m.on('dragend',ev=>{const j=markers.indexOf(m),s=snapPoint(ev.target.getLatLng());pts[j]=s.ll;locks[j]=s.snapped;m.setLatLng(s.ll);rebuildMarkers();redraw();if(s.snapped)toast('🧲 snapped and locked')});return m}
  function rebuildMarkers(){markers.forEach(m=>map.removeLayer(m));markers=[];pts.forEach((p,i)=>{const m=makeMarker(p,i).addTo(map);markers.push(m)})}
  function insertOnCurrent(ll){if(pts.length<2)return false;const cp=map.latLngToContainerPoint(ll);let k=-1,d0=25,q=null;for(let i=0;i<pts.length;i++){const a=map.latLngToContainerPoint(pts[i]),b=map.latLngToContainerPoint(pts[(i+1)%pts.length]),dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((cp.x-a.x)*dx+(cp.y-a.y)*dy)/l2)),x=a.x+dx*t,y=a.y+dy*t,d=Math.hypot(x-cp.x,y-cp.y);if(d<d0){d0=d;k=i;q=map.containerPointToLatLng(L.point(x,y))}}if(k<0)return false;pts.splice(k+1,0,q);pointMeta.splice(k+1,0,nextMeta());locks.splice(k+1,0,false);rebuildMarkers();fitted=false;redraw();return true}

  map.on('click',e=>{
    if(pickMode){pickPts.push(e.latlng);drawCutPreview();if(pickPts.length===2){toast(pickMode==='parallel'?'Line direction ready — press Split':'Pivot and direction ready — press Split')}return}
    if(mode==='insert'){if(!insertOnCurrent(e.latlng))toast('Tap close to a current edge');return}
    if(mode!=='draw')return;const s=snapPoint(e.latlng);pts.push(s.ll);locks.push(s.snapped);pointMeta.push(nextMeta());fitted=false;rebuildMarkers();redraw();if(s.snapped)toast('🧲 snapped point locked')
  });
  function updateLabel(area){if(labelMarker)map.removeLayer(labelMarker);labelMarker=null;if(pts.length<3)return;const sb=document.getElementById('sbKey').value.trim(),txt=(sb?htmlEsc(sb)+' | ':'')+arpText(area);labelMarker=L.marker(centroid(pts),{interactive:false,icon:L.divIcon({className:'',html:`<div class="lblbadge">${txt}</div>`,iconSize:[0,0]})}).addTo(map)}
  function updateCoords(){const tb=document.getElementById('coordBody');tb.innerHTML='';pts.forEach((p,i)=>{let en=['—','—'];try{en=toSLD(p)}catch(e){}const m=pointMeta[i]||{};tb.insertAdjacentHTML('beforeend',`<tr><td>${htmlEsc(m.no||i+1)}</td><td>${htmlEsc(m.code||'')}</td><td>${p.lat.toFixed(7)}</td><td>${p.lng.toFixed(7)}</td><td>${typeof en[0]==='number'?en[0].toFixed(3):en[0]}</td><td>${typeof en[1]==='number'?en[1].toFixed(3):en[1]}</td></tr>`)})}
  function redraw(){if(poly)map.removeLayer(poly);poly=null;if(pts.length>=2)poly=L.polygon(pts,{color:'#ffb64d',weight:2,fill:true,fillColor:'#ffb64d',fillOpacity:.12}).addTo(map);const a=pts.length>=3?ringAreaM2(pts):0;document.getElementById('drawnArea').textContent=arpText(a);document.getElementById('fitBtn').disabled=pts.length<3;document.getElementById('addBtn').disabled=pts.length<3;updateLabel(a);updateCoords();autoSave()}
  function clearWorking(){pts=[];pointMeta=[];locks=[];markers.forEach(m=>map.removeLayer(m));markers=[];if(poly)map.removeLayer(poly);poly=null;if(labelMarker)map.removeLayer(labelMarker);labelMarker=null;fitted=false;clearCut();redraw()}

  function drawSaved(land,index){land.layer=L.polygon(land.pts,{color:'#2fb3a3',weight:2,fill:true,fillColor:'#2fb3a3',fillOpacity:.14}).addTo(map);land.lbl=L.marker(centroid(land.pts),{interactive:false,icon:L.divIcon({className:'',html:`<div class="lblbadge">${htmlEsc(land.sb?land.sb+' | ':'')}${arpText(land.area)}</div>`,iconSize:[0,0]})}).addTo(map);land.layer.on('click',()=>{if(mode!=='pan'||!confirm('Open this land for edit / split?'))return;loadLandForEdit(index)})}
  function rebuildSaved(){savedLands.forEach(x=>{if(x.layer)map.removeLayer(x.layer);if(x.lbl)map.removeLayer(x.lbl)});savedLands.forEach((x,i)=>drawSaved(x,i));refreshSavedUI()}
  function loadLandForEdit(i){const l=savedLands[i];if(!l)return;savedLands.splice(i,1);if(l.layer)map.removeLayer(l.layer);if(l.lbl)map.removeLayer(l.lbl);pts=l.pts.map(p=>L.latLng(p.lat,p.lng));pointMeta=(l.meta||[]).map(x=>({...x}));while(pointMeta.length<pts.length)pointMeta.push({no:String(pointMeta.length+1),code:''});locks=pts.map(()=>false);document.getElementById('sbKey').value=l.sb||'';document.getElementById('remark').value=l.remark||'';const ar=m2ToARP(l.area);document.getElementById('A').value=ar.A;document.getElementById('R').value=ar.R;document.getElementById('P').value=ar.P.toFixed(2);rebuildMarkers();rebuildSaved();redraw();map.fitBounds(L.latLngBounds(pts),{padding:[35,35]});toast('Land opened for edit')}
  function refreshSavedUI(){document.getElementById('savedCnt').textContent=savedLands.length;document.getElementById('kmlBtn').disabled=savedLands.length===0&&pts.length<3}

  ['A','R','P'].forEach(id=>document.getElementById(id).addEventListener('input',()=>document.getElementById('tgtArea').textContent=arpText(targetM2())));
  document.getElementById('sbKey').addEventListener('input',()=>updateLabel(ringAreaM2(pts)));
  document.getElementById('fitBtn').onclick=()=>{if(pts.length<3)return;const tgt=targetM2(),cur=ringAreaM2(pts);if(tgt<=0||cur<=0){toast('Type a valid target extent first');return}const base=pts.map(p=>L.latLng(p.lat,p.lng)),fixed=base.filter((_,i)=>locks[i]);if(fixed.length===base.length){if(Math.abs(cur-tgt)<0.05)toast('Already at target area');else toast('All vertices are snapped/locked — unlock by dragging required points');return}const c=fixed.length?centroid(fixed):centroid(base),mlat=110540,mlon=111320*Math.cos(c.lat*Math.PI/180);const at=f=>base.map((p,i)=>locks[i]?L.latLng(p.lat,p.lng):L.latLng(c.lat+((p.lat-c.lat)*mlat*f)/mlat,c.lng+((p.lng-c.lng)*mlon*f)/mlon));let lo=0,hi=1,a0=ringAreaM2(at(0)),ah=ringAreaM2(at(hi));if(tgt<a0-0.05){toast('Target is too small while snapped points stay fixed');return}while(ah<tgt&&hi<1024){hi*=2;ah=ringAreaM2(at(hi))}if(ah<tgt){toast('Target could not be reached with locked points');return}for(let n=0;n<70;n++){const mid=(lo+hi)/2;if(ringAreaM2(at(mid))<tgt)lo=mid;else hi=mid}pts=at((lo+hi)/2);rebuildMarkers();fitted=true;redraw();toast(`Fitted: ${arpText(ringAreaM2(pts))} · ${fixed.length} snapped point(s) unchanged`)};
  document.getElementById('undo').onclick=()=>{if(!pts.length)return;pts.pop();locks.pop();pointMeta.pop();rebuildMarkers();fitted=false;redraw()};
  document.getElementById('clrBtn').onclick=clearWorking;
  document.getElementById('joinBtn').onclick=()=>{if(pts.length<3)return toast('At least 3 measured points required');redraw();map.fitBounds(L.latLngBounds(pts),{padding:[30,30]});toast('Measured points joined as polygon')};
  document.getElementById('addBtn').onclick=()=>{if(pts.length<3)return;if(targetM2()>0&&!fitted&&!confirm('Fit to Extent කරලා නෑ. Current size එකෙන් save කරන්නද?'))return;const land={sb:document.getElementById('sbKey').value.trim(),remark:document.getElementById('remark').value.trim(),area:ringAreaM2(pts),pts:pts.map(p=>L.latLng(p.lat,p.lng)),meta:pointMeta.map(x=>({...x}))};savedLands.push(land);clearWorking();document.getElementById('sbKey').value='';document.getElementById('remark').value='';['A','R','P'].forEach(id=>document.getElementById(id).value=0);document.getElementById('tgtArea').textContent=arpText(0);rebuildSaved();autoSave();toast('✅ Land saved in current job')};
  document.getElementById('snapTgl').onclick=()=>{snapOn=!snapOn;document.getElementById('snapTgl').textContent='🧲 Snap: '+(snapOn?'ON':'OFF');toast('Boundary snap '+(snapOn?'ON':'OFF'))};
  document.getElementById('delAllBtn').onclick=()=>{if(!savedLands.length)return toast('No saved lands');if(!confirm(`Saved lands ${savedLands.length}ම මකන්නද?`))return;savedLands=[];rebuildSaved();autoSave();toast('Saved lands cleared')};

  function clearCut(){if(cutLayer)map.removeLayer(cutLayer);cutLayer=null;pickMode='';pickPts=[]}
  function drawCutPreview(){if(cutLayer)map.removeLayer(cutLayer);if(pickPts.length<2)return;const a=pickPts[0],b=pickPts[1],dx=b.lng-a.lng,dy=b.lat-a.lat;cutLayer=L.polyline([[a.lat-dy*50,a.lng-dx*50],[a.lat+dy*50,a.lng+dx*50]],{className:'cutline',color:'#ff6b6b',dashArray:'7,5',weight:2}).addTo(map)}
  function areaXY(q){let s=0;for(let i=0;i<q.length;i++){const a=q[i],b=q[(i+1)%q.length];s+=a[0]*b[1]-b[0]*a[1]}return Math.abs(s)/2}
  function clipHalf(q,a,b,positive){const out=[],side=p=>(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]),inside=p=>positive?side(p)>=-1e-8:side(p)<=1e-8;for(let i=0;i<q.length;i++){const p=q[i],r=q[(i+1)%q.length],ip=inside(p),ir=inside(r);if(ip)out.push(p);if(ip!==ir){const sp=side(p),sr=side(r),t=sp/(sp-sr);out.push([p[0]+(r[0]-p[0])*t,p[1]+(r[1]-p[1])*t])}}return out}
  function applySplit(one,two,kind){if(one.length<3||two.length<3)return toast('Cut does not cross the polygon correctly');const sb=document.getElementById('sbKey').value.trim()||'Split',remark=document.getElementById('remark').value.trim();const mk=(q,n)=>{const ll=q.map(p=>fromSLD(p[0],p[1]));return{sb:`${sb}-${n}`,remark:`${remark}${remark?' · ':''}${kind}`,area:ringAreaM2(ll),pts:ll,meta:ll.map((_,i)=>({no:String(i+1),code:''}))}};savedLands.push(mk(one,1),mk(two,2));clearWorking();rebuildSaved();autoSave();toast(`${kind}: 2 lands created`)}
  function splitParallel(){if(pts.length<3||pickPts.length<2)return toast('Draw/open a polygon and pick the cut direction');const tgt=targetM2(),q=pts.map(toSLD);if(tgt<=0||tgt>=areaXY(q))return toast('Split extent must be > 0 and smaller than full land');let a=toSLD(pickPts[0]),b=toSLD(pickPts[1]),dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy);if(len<.01)return toast('Cut line points are too close');const nx=-dy/len,ny=dx/len,proj=q.map(p=>p[0]*nx+p[1]*ny),base=a[0]*nx+a[1]*ny;let lo=Math.min(...proj)-base-1,hi=Math.max(...proj)-base+1;for(let i=0;i<70;i++){const d=(lo+hi)/2,A=[a[0]+nx*d,a[1]+ny*d],B=[b[0]+nx*d,b[1]+ny*d],ar=areaXY(clipHalf(q,A,B,true));if(ar>tgt)lo=d;else hi=d}const d=(lo+hi)/2,A=[a[0]+nx*d,a[1]+ny*d],B=[b[0]+nx*d,b[1]+ny*d];applySplit(clipHalf(q,A,B,true),clipHalf(q,A,B,false),'Parallel split');clearCut()}
  function splitRotate(){if(pts.length<3||pickPts.length<2)return toast('Draw/open a polygon and pick pivot + direction');const tgt=targetM2(),q=pts.map(toSLD),total=areaXY(q);if(tgt<=0||tgt>=total)return toast('Split extent must be > 0 and smaller than full land');const p=toSLD(pickPts[0]),d0=toSLD(pickPts[1]),base=Math.atan2(d0[1]-p[1],d0[0]-p[0]);let best={err:Infinity,t:0},cross=null,prev=null;for(let i=0;i<=720;i++){const t=Math.PI*i/720,b=[p[0]+Math.cos(base+t),p[1]+Math.sin(base+t)],v=areaXY(clipHalf(q,p,b,true))-tgt;if(Math.abs(v)<best.err)best={err:Math.abs(v),t};if(prev&&v*prev.v<=0){cross=[prev.t,t];break}prev={t,v}}let t=best.t;if(cross){let[lo,hi]=cross;let vlo=areaXY(clipHalf(q,p,[p[0]+Math.cos(base+lo),p[1]+Math.sin(base+lo)],true))-tgt;for(let i=0;i<65;i++){const mid=(lo+hi)/2,v=areaXY(clipHalf(q,p,[p[0]+Math.cos(base+mid),p[1]+Math.sin(base+mid)],true))-tgt;if(v*vlo<=0)hi=mid;else{lo=mid;vlo=v}}t=(lo+hi)/2}const b=[p[0]+Math.cos(base+t),p[1]+Math.sin(base+t)],one=clipHalf(q,p,b,true),two=clipHalf(q,p,b,false);if(Math.abs(areaXY(one)-tgt)>.25)return toast('This pivot cannot produce that extent — choose another pivot');applySplit(one,two,'Rotate split');clearCut()}
  document.getElementById('parallelPickBtn').onclick=()=>{pickMode='parallel';pickPts=[];clearCut();pickMode='parallel';mode='pan';toast('Tap 2 points for cut direction')};
  document.getElementById('rotatePickBtn').onclick=()=>{pickMode='rotate';pickPts=[];clearCut();pickMode='rotate';mode='pan';toast('Tap pivot first, then direction point')};
  document.getElementById('parallelSplitBtn').onclick=splitParallel;document.getElementById('rotateSplitBtn').onclick=splitRotate;

  let meMarker=null,meAcc=null;const secure=()=>window.isSecureContext||location.protocol==='https:'||location.hostname==='localhost';
  function showPosition(pos,center){const ll=L.latLng(pos.coords.latitude,pos.coords.longitude);lastGps=pos;if(meMarker)map.removeLayer(meMarker);if(meAcc)map.removeLayer(meAcc);meAcc=L.circle(ll,{radius:pos.coords.accuracy||10,color:'#2fb3a3',weight:1,fillColor:'#2fb3a3',fillOpacity:.15}).addTo(map);meMarker=L.circleMarker(ll,{radius:7,color:'#fff',weight:2,fillColor:'#2fb3a3',fillOpacity:1}).addTo(map);if(center)map.setView(ll,19)}
  document.getElementById('gps').onclick=()=>{if(!secure())return toast('GPS requires the https GitHub Pages link');navigator.geolocation.getCurrentPosition(p=>{showPosition(p,true);toast(`Location ±${Math.round(p.coords.accuracy)}m`)},e=>toast('GPS: '+e.message),{enableHighAccuracy:true,timeout:15000,maximumAge:0})};
  function addGps(pos,force){showPosition(pos,false);const ll=L.latLng(pos.coords.latitude,pos.coords.longitude);if(!force&&pts.length&&map.distance(pts[pts.length-1],ll)<1)return;pts.push(ll);locks.push(false);pointMeta.push(nextMeta());rebuildMarkers();redraw();document.getElementById('walkStatus').textContent=`Recording · ${pts.length} points · accuracy ±${Math.round(pos.coords.accuracy)}m`}
  document.getElementById('walkStartBtn').onclick=()=>{if(!secure())return toast('GPS walk requires https');if(walkWatch!==null)return;clearWorking();walkWatch=navigator.geolocation.watchPosition(p=>addGps(p,false),e=>toast('GPS: '+e.message),{enableHighAccuracy:true,maximumAge:0,timeout:20000});document.getElementById('walkStatus').textContent='Recording… walk around the land';toast('GPS walk started')};
  document.getElementById('walkPointBtn').onclick=()=>{if(lastGps)addGps(lastGps,true);else toast('No GPS position yet')};
  document.getElementById('walkStopBtn').onclick=()=>{if(walkWatch!==null){navigator.geolocation.clearWatch(walkWatch);walkWatch=null}redraw();document.getElementById('walkStatus').textContent=`Stopped · ${pts.length} points joined`;toast(pts.length>=3?'GPS polygon joined':'Need at least 3 GPS points')};

  function jobData(){return{name:document.getElementById('jobName').value.trim()||'Untitled Job',updated:new Date().toISOString(),saved:savedLands.map(l=>({sb:l.sb,remark:l.remark,area:l.area,pts:l.pts.map(p=>[p.lat,p.lng]),meta:l.meta||[]})),draft:{sb:document.getElementById('sbKey').value,remark:document.getElementById('remark').value,pts:pts.map(p=>[p.lat,p.lng]),meta:pointMeta,locks},refs:referenceRings.map(r=>r.map(p=>[p.lat,p.lng]))}}
  function jobs(){try{return JSON.parse(localStorage.getItem(JOBS_KEY)||'{}')}catch(e){return{}}}
  function populateJobs(){const j=jobs(),s=document.getElementById('jobSel'),v=s.value;s.innerHTML='<option value="">Open job…</option>'+Object.entries(j).sort((a,b)=>(b[1].updated||'').localeCompare(a[1].updated||'')).map(([id,x])=>`<option value="${id}">${htmlEsc(x.name)}</option>`).join('');s.value=v}
  function saveJob(show=true){if(!currentJobId)currentJobId='job_'+Date.now();const j=jobs();j[currentJobId]=jobData();localStorage.setItem(JOBS_KEY,JSON.stringify(j));localStorage.setItem(LAST_JOB_KEY,currentJobId);populateJobs();document.getElementById('jobSel').value=currentJobId;if(show)toast('Job saved on this device')}
  function autoSave(){if(currentJobId)try{saveJob(false)}catch(e){}}
  function resetMapData(){const oldJob=currentJobId;currentJobId='';clearWorking();savedLands=[];rebuildSaved();referenceRings=[];referenceLayers.forEach(x=>map.removeLayer(x));referenceLayers=[];currentJobId=oldJob}
  function openJob(id){const d=jobs()[id];if(!d)return toast('Job not found');resetMapData();currentJobId=id;document.getElementById('jobName').value=d.name||'';savedLands=(d.saved||[]).map(x=>({sb:x.sb||'',remark:x.remark||'',area:x.area||0,pts:x.pts.map(p=>L.latLng(p[0],p[1])),meta:x.meta||[]}));const w=d.draft||{};pts=(w.pts||[]).map(p=>L.latLng(p[0],p[1]));pointMeta=w.meta||[];locks=w.locks||pts.map(()=>false);document.getElementById('sbKey').value=w.sb||'';document.getElementById('remark').value=w.remark||'';referenceRings=(d.refs||[]).map(r=>r.map(p=>L.latLng(p[0],p[1])));drawReferences();rebuildSaved();rebuildMarkers();redraw();const all=savedLands.flatMap(x=>x.pts).concat(pts,referenceRings.flat());if(all.length)map.fitBounds(L.latLngBounds(all),{padding:[30,30]});document.getElementById('jobSel').value=id;toast('Job opened: '+d.name)}
  document.getElementById('saveJobBtn').onclick=()=>saveJob(true);document.getElementById('openJobBtn').onclick=()=>{const id=document.getElementById('jobSel').value;if(id)openJob(id);else toast('Select a job')};
  document.getElementById('newJobBtn').onclick=()=>{if((savedLands.length||pts.length)&&!confirm('Start a new job? Current job will be saved first.'))return;if(currentJobId)saveJob(false);resetMapData();currentJobId='job_'+Date.now();document.getElementById('jobName').value='Job '+new Date().toLocaleDateString();document.getElementById('sbKey').value='';document.getElementById('remark').value='';saveJob(false);toast('New job ready')};

  function currentLands(){const a=savedLands.map(x=>x);if(pts.length>=3)a.push({sb:document.getElementById('sbKey').value.trim(),remark:document.getElementById('remark').value.trim(),area:ringAreaM2(pts),pts:pts.slice(),meta:pointMeta.slice()});return a}
  function exportKML(){const lands=currentLands();if(!lands.length)return toast('No lands to export');let body='';lands.forEach((l,i)=>{const ring=l.pts.concat([l.pts[0]]),coords=ring.map(p=>`${p.lng.toFixed(9)},${p.lat.toFixed(9)},0`).join(' '),name=l.sb||`Lot ${i+1}`,c=centroid(l.pts);body+=`<Placemark><name>${xmlEsc(name)}</name><description><![CDATA[<b>Extent:</b> ${arpText(l.area)}<br><b>Remark:</b> ${htmlEsc(l.remark||'')}]]></description><styleUrl>#p</styleUrl><Polygon><outerBoundaryIs><LinearRing><coordinates>${coords}</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark><Placemark><name>${xmlEsc(name+' | '+arpText(l.area))}</name><styleUrl>#l</styleUrl><Point><coordinates>${c.lng},${c.lat},0</coordinates></Point></Placemark>`});const k=`<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${xmlEsc(document.getElementById('jobName').value||'Field lands')}</name><Style id="p"><LineStyle><color>ff00d0ff</color><width>3</width></LineStyle><PolyStyle><color>3300d0ff</color></PolyStyle></Style><Style id="l"><LabelStyle><scale>1.2</scale></LabelStyle></Style>${body}</Document></kml>`;downloadText(k,(document.getElementById('jobName').value||'field_lands').replace(/[^\w-]+/g,'_')+'.kml','application/vnd.google-earth.kml+xml');toast('KML exported in WGS84')}
  document.getElementById('kmlBtn').onclick=exportKML;
  function exportDXF(){const lands=currentLands();if(!lands.length)return toast('No lands to export');if(!window.proj4)return toast('SLD99 converter is unavailable');const pair=(c,v)=>`${c}\n${v}\n`,oneLine=v=>String(v||'').replace(/[\r\n]+/g,' ');let e='';lands.forEach((l,i)=>{const q=l.pts.map(toSLD),name=oneLine(l.sb||`LOT_${i+1}`);e+=pair(0,'POLYLINE')+pair(8,'BOUND-OTHER-GEN')+pair(66,1)+pair(70,1);q.forEach(p=>e+=pair(0,'VERTEX')+pair(8,'BOUND-OTHER-GEN')+pair(10,p[0].toFixed(3))+pair(20,p[1].toFixed(3))+pair(30,'0'));e+=pair(0,'SEQEND');const c=toSLD(centroid(l.pts));e+=pair(0,'TEXT')+pair(8,'TEXT-LOT')+pair(10,c[0].toFixed(3))+pair(20,c[1].toFixed(3))+pair(30,0)+pair(40,2)+pair(1,name);if(l.remark)e+=pair(0,'TEXT')+pair(8,'TEXT-REMARK')+pair(10,c[0].toFixed(3))+pair(20,(c[1]-3).toFixed(3))+pair(30,0)+pair(40,1.5)+pair(1,oneLine(l.remark))});const d=pair(0,'SECTION')+pair(2,'HEADER')+pair(9,'$ACADVER')+pair(1,'AC1009')+pair(0,'ENDSEC')+pair(0,'SECTION')+pair(2,'ENTITIES')+e+pair(0,'ENDSEC')+pair(0,'EOF');downloadText(d,(document.getElementById('jobName').value||'field_lands').replace(/[^\w-]+/g,'_')+'_SLD99.dxf','application/dxf');toast('DXF exported — SLD99 / EPSG:5235')}
  document.getElementById('dxfExportBtn').onclick=exportDXF;

  function parseKML(text){const x=new DOMParser().parseFromString(text,'application/xml');if(x.querySelector('parsererror'))throw Error('Invalid KML');const out=[];x.querySelectorAll('Placemark').forEach(pm=>{const c=pm.querySelector('Polygon coordinates');if(!c)return;let q=c.textContent.trim().split(/\s+/).map(s=>s.split(',')).filter(v=>v.length>=2).map(v=>L.latLng(+v[1],+v[0]));if(q.length>1&&q[0].equals(q[q.length-1]))q.pop();if(q.length>=3)out.push({name:(pm.querySelector('name')||{}).textContent||'',remark:(pm.querySelector('description')||{}).textContent||'',pts:q})});return out}
  function importKML(text,reference){const arr=parseKML(text);if(!arr.length)throw Error('No polygon found');if(reference){arr.forEach(x=>referenceRings.push(x.pts));drawReferences();toast(`${arr.length} reference polygon(s) added`)}else{arr.forEach(x=>savedLands.push({sb:x.name,remark:x.remark,area:ringAreaM2(x.pts),pts:x.pts,meta:x.pts.map((_,i)=>({no:String(i+1),code:''}))}));rebuildSaved();autoSave();map.fitBounds(L.latLngBounds(arr.flatMap(x=>x.pts)),{padding:[30,30]});toast(`${arr.length} KML land(s) imported — WGS84`)} }
  function drawReferences(){referenceLayers.forEach(x=>map.removeLayer(x));referenceLayers=referenceRings.map(r=>L.polygon(r,{color:'#c084fc',weight:2,dashArray:'6,5',fill:false,interactive:false}).addTo(map));autoSave()}
  function parseDXF(text){const ln=text.replace(/\r/g,'').split('\n'),p=[];for(let i=0;i+1<ln.length;i+=2)p.push([ln[i].trim(),ln[i+1].trim()]);const out=[];for(let i=0;i<p.length;i++){if(p[i][0]!=='0')continue;if(p[i][1]==='LWPOLYLINE'){const q=[];let x=null,closed=false;i++;for(;i<p.length&&p[i][0]!=='0';i++){if(p[i][0]==='70')closed=(+p[i][1]&1)!==0;if(p[i][0]==='10')x=+p[i][1];if(p[i][0]==='20'&&x!==null){q.push([x,+p[i][1]]);x=null}}i--;if(q.length>=3)out.push(q)}else if(p[i][1]==='POLYLINE'){const q=[];i++;for(;i<p.length;i++){if(p[i][0]==='0'&&p[i][1]==='SEQEND')break;if(p[i][0]==='0'&&p[i][1]==='VERTEX'){let x=null,y=null;i++;for(;i<p.length&&p[i][0]!=='0';i++){if(p[i][0]==='10')x=+p[i][1];if(p[i][0]==='20')y=+p[i][1]}i--;if(Number.isFinite(x)&&Number.isFinite(y))q.push([x,y])}}if(q.length>=3)out.push(q)}}return out}
  function importDXF(text,name){if(!window.proj4)throw Error('SLD99 converter unavailable');const a=parseDXF(text);if(!a.length)throw Error('No closed polyline polygon found');a.forEach((q,i)=>{const ll=q.map(p=>fromSLD(p[0],p[1]));savedLands.push({sb:`${name.replace(/\.dxf$/i,'')}-${i+1}`,remark:'Imported DXF · SLD99',area:ringAreaM2(ll),pts:ll,meta:ll.map((_,j)=>({no:String(j+1),code:''}))})});rebuildSaved();autoSave();map.fitBounds(L.latLngBounds(a.flat().map(p=>fromSLD(p[0],p[1]))),{padding:[30,30]});toast(`${a.length} DXF polygon(s) imported — SLD99`)}
  const fileIn=document.getElementById('fileIn');let importType='';function choose(type,accept){importType=type;fileIn.accept=accept;fileIn.value='';fileIn.click()}
  document.getElementById('dxfImportBtn').onclick=()=>choose('dxf','.dxf');document.getElementById('kmlImportBtn').onclick=()=>choose('kml','.kml');document.getElementById('refKmlBtn').onclick=()=>choose('ref','.kml');
  fileIn.onchange=async()=>{const f=fileIn.files[0];if(!f)return;try{const t=await f.text();if(importType==='dxf')importDXF(t,f.name);else importKML(t,importType==='ref')}catch(e){toast('Import failed: '+e.message)}};
  document.getElementById('coordCsvBtn').onclick=()=>{const lands=currentLands();if(!lands.length)return toast('No coordinates');let c='Land,Point,Code,Latitude_WGS84,Longitude_WGS84,Easting_SLD99,Northing_SLD99\r\n';lands.forEach((l,k)=>l.pts.forEach((p,i)=>{const m=(l.meta||[])[i]||{},en=toSLD(p);c+=`"${String(l.sb||k+1).replace(/"/g,'""')}","${m.no||i+1}","${String(m.code||'').replace(/"/g,'""')}",${p.lat.toFixed(7)},${p.lng.toFixed(7)},${en[0].toFixed(3)},${en[1].toFixed(3)}\r\n`}));downloadText(c,(document.getElementById('jobName').value||'coordinates')+'_WGS84_SLD99.csv','text/csv');toast('Coordinate CSV exported')};

  const sheet=document.getElementById('sheet');function syncSheet(){const h=sheet.classList.contains('collapsed')?46:Math.min(sheet.offsetHeight,innerHeight*.62);document.documentElement.style.setProperty('--sheetH',h+'px');setTimeout(()=>map.invalidateSize(),260)}function toggleSheet(){sheet.classList.toggle('collapsed');document.getElementById('sheetTgl').textContent=sheet.classList.contains('collapsed')?'▴':'▾';syncSheet()}document.getElementById('sheetTgl').onclick=toggleSheet;document.getElementById('grip').onclick=toggleSheet;addEventListener('resize',syncSheet);new ResizeObserver(syncSheet).observe(sheet);
  document.getElementById('tgtArea').textContent=arpText(targetM2());populateJobs();refreshSavedUI();syncSheet();const last=localStorage.getItem(LAST_JOB_KEY);if(last&&jobs()[last])openJob(last);else{currentJobId='job_'+Date.now();document.getElementById('jobName').value='Job '+new Date().toLocaleDateString();saveJob(false)}
  if(!window.proj4)setTimeout(()=>toast('Warning: SLD99 converter could not load'),800)
}
