'use strict';
const $=id=>document.getElementById(id),PERCH_M2=25.29285264,ACRE=160,ROOD=40;
const PROJECTS_KEY='fieldsketch_projects_v3',ACTIVE_KEY='fieldsketch_active_v3',CODES_KEY='fieldsketch_codes_v3',LIC_KEY='fieldsketch_lic',LEGACY_LIC_KEY='rub'+'ber_lic';
const LIC_SECRET='RSK-bxNNco6NYy56aJ8n9L91D-9WOqVKNlp9-2026',TRIAL_DAYS=3;
const SLD99='+proj=tmerc +lat_0=7.00047152777778 +lon_0=80.7717130833333 +k=0.9999238418 +x_0=500000 +y_0=500000 +ellps=evrst30 +towgs84=-0.293,766.95,87.713,-0.195704,-1.695068,-3.473016,-0.039338 +units=m +no_defs +type=crs';
if(window.proj4)proj4.defs('EPSG:5235',SLD99);
const uid=p=>(p||'id')+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const xml=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const arpToM2=(a,r,p)=>(a*ACRE+r*ROOD+p)*PERCH_M2;
function m2ToARP(m){let p=m/PERCH_M2,a=Math.floor(p/ACRE);p-=a*ACRE;let r=Math.floor(p/ROOD);p-=r*ROOD;return{a,r,p}}
function arpText(m){const x=m2ToARP(Math.max(0,m||0));return`${x.a}A ${x.r}R ${x.p.toFixed(2)}P`}
function ringArea(c){if(c.length<3)return 0;const R=6378137;let s=0;for(let i=0;i<c.length;i++){const a=c[i],b=c[(i+1)%c.length];s+=(b[0]-a[0])*Math.PI/180*(2+Math.sin(a[1]*Math.PI/180)+Math.sin(b[1]*Math.PI/180))}return Math.abs(s*R*R/2)}
function lineLength(c){let s=0;for(let i=1;i<c.length;i++)s+=distance(c[i-1],c[i]);return s}
function distance(a,b){const r=6371008.8,p1=a[1]*Math.PI/180,p2=b[1]*Math.PI/180,dp=(b[1]-a[1])*Math.PI/180,dl=(b[0]-a[0])*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*r*Math.asin(Math.sqrt(h))}
function centroid(c){let x=0,y=0,z=0;c.forEach(p=>{const la=p[1]*Math.PI/180,lo=p[0]*Math.PI/180;x+=Math.cos(la)*Math.cos(lo);y+=Math.cos(la)*Math.sin(lo);z+=Math.sin(la)});return[Math.atan2(y,x)*180/Math.PI,Math.atan2(z,Math.hypot(x,y))*180/Math.PI]}
function toSLD(p){if(!window.proj4)throw Error('SLD99 converter unavailable');return proj4('EPSG:4326','EPSG:5235',p)}
function fromSLD(p){if(!window.proj4)throw Error('SLD99 converter unavailable');return proj4('EPSG:5235','EPSG:4326',p)}
function download(text,name,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
let toastTimer;function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}

function b64u(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64str(s){return decodeURIComponent(escape(atob(s.replace(/-/g,'+').replace(/_/g,'/'))))}
async function hmac(s){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(LIC_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(s)))}
async function deviceId(){const s=[navigator.userAgent,navigator.platform,navigator.language,screen.width+'x'+screen.height,screen.colorDepth,Intl.DateTimeFormat().resolvedOptions().timeZone||''].join('|');return b64u(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).slice(0,16)}
const today=()=>new Date().toISOString().slice(0,10),dayDiff=(a,b)=>Math.floor((new Date(b+'T00:00:00Z')-new Date(a+'T00:00:00Z'))/86400000);
async function verifyKey(k){try{const[p,m]=k.trim().split('.');if(!p||!m||await hmac(p)!==m)return null;return JSON.parse(b64str(p))}catch(e){return null}}
async function licenceGate(){const modal=$('licenceModal'),msg=$('licenceMsg'),inputs=$('licenceInputs'),dev=await deviceId();$('deviceId').textContent=dev;modal.classList.add('show');const saved=localStorage.getItem(LIC_KEY)||localStorage.getItem(LEGACY_LIC_KEY);if(saved&&!localStorage.getItem(LIC_KEY))localStorage.setItem(LIC_KEY,saved);if(saved&&saved.includes('.')){const p=await verifyKey(saved);if(p&&(!p.d||p.d===dev)&&today()<=p.exp){modal.classList.remove('show');return boot()}}if(saved&&saved.startsWith('trial:')&&dayDiff(saved.slice(6),today())<TRIAL_DAYS){modal.classList.remove('show');return boot()}msg.textContent=saved?'Licence/trial expired or invalid. Enter a valid key.':'Enter a licence key or start the 3-day trial.';inputs.classList.remove('hidden');$('activateBtn').onclick=async()=>{const p=await verifyKey($('licenceKey').value);if(!p)return msg.textContent='Invalid licence key.';if(p.d&&p.d!==dev)return msg.textContent='This licence belongs to another device.';if(today()>p.exp)return msg.textContent='Licence expired on '+p.exp;localStorage.setItem(LIC_KEY,$('licenceKey').value.trim());modal.classList.remove('show');boot()};$('trialBtn').onclick=()=>{if(saved&&saved.startsWith('trial:'))return msg.textContent='Trial already used on this device.';localStorage.setItem(LIC_KEY,'trial:'+today());modal.classList.remove('show');boot()};$('copyDeviceBtn').onclick=async()=>{try{await navigator.clipboard.writeText(dev);toast('Device ID copied')}catch(e){toast('Copy unavailable')}}}

function boot(){
 const map=L.map('map',{zoomControl:false,attributionControl:false,tap:false}).setView([7.1731,80.3050],16);
 const google=L.tileLayer('https://mt{s}.google.com/vt/lyrs=y&x={x}&y={y}&z={z}',{subdomains:['0','1','2','3'],maxZoom:21,maxNativeZoom:21}).addTo(map),esri=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:21,maxNativeZoom:19});let tileErrors=0;google.on('tileerror',()=>{if(++tileErrors===6){map.removeLayer(google);esri.addTo(map);toast('Esri imagery loaded')}});
 const featureGroup=L.layerGroup().addTo(map),draftGroup=L.layerGroup().addTo(map),previewGroup=L.layerGroup().addTo(map),gpsGroup=L.layerGroup().addTo(map);
 let projects=loadProjects(),project=null,selectedId='',mode='select',draft=null,editingId='',featureViews=new Map(),preview=null,picks=[],traceStart=null,lastGps=null,walkId=null,fileMode='',saveTimer=null,assembleIds=[],assembleCoords=[];
 const typeInfo={parcel:['Parcel','Polygon','#2fb3a3'],building:['Building','Polygon','#ff9f43'],boundary:['Boundary','LineString','#ffb64d'],road:['Road','LineString','#6eb7ff'],footpath:['Footpath','LineString','#d4b483'],stream:['Stream','LineString','#4da3ff'],drain:['Drain','LineString','#66c2ff'],fence:['Fence','LineString','#d0d0d0'],'custom-line':['Custom line','LineString','#bd8cff'],point:['Survey point','Point','#ff6b6b'],note:['Note','Point','#bd8cff']};
 function loadProjects(){try{return JSON.parse(localStorage.getItem(PROJECTS_KEY)||'{}')}catch(e){return{}}}
 function defaultProject(name){return{schema:'fieldsketch-project',version:3,id:uid('project'),name:name||'New Project',created:new Date().toISOString(),updated:new Date().toISOString(),layers:[{id:uid('lyr'),name:'Parcels',kind:'parcel',color:'#2fb3a3',visible:true,locked:false,snap:true,export:true,source:'survey'},{id:uid('lyr'),name:'Survey Points',kind:'point',color:'#ff6b6b',visible:true,locked:false,snap:true,export:true,source:'survey'},{id:uid('lyr'),name:'Roads & Paths',kind:'line',color:'#6eb7ff',visible:true,locked:false,snap:true,export:true,source:'survey'},{id:uid('lyr'),name:'Streams & Drains',kind:'line',color:'#4da3ff',visible:true,locked:false,snap:true,export:true,source:'survey'},{id:uid('lyr'),name:'Reference',kind:'reference',color:'#bd8cff',visible:true,locked:true,snap:true,export:false,source:'reference'}],features:[]}}
 function migrateLegacyJobs(){let old;try{old=JSON.parse(localStorage.getItem('fieldsketch_jobs_v2')||'{}')}catch(e){old={}}Object.values(old).forEach(j=>{const p=defaultProject(j.name||'Migrated Project'),parcel=p.layers.find(x=>x.kind==='parcel'),ref=p.layers.find(x=>x.kind==='reference');(j.saved||[]).forEach((x,i)=>{const c=(x.pts||[]).map(v=>[v[1],v[0]]);if(c.length>=3)p.features.push({id:uid('feature'),layerId:parcel.id,type:'parcel',geometry:'Polygon',coords:c,vertexLocks:c.map(()=>false),locked:false,properties:{name:x.sb||`Parcel ${i+1}`,remark:x.remark||''},created:new Date().toISOString()})});(j.refs||[]).forEach((r,i)=>{const c=r.map(v=>[v[1],v[0]]);if(c.length>=2)p.features.push({id:uid('feature'),layerId:ref.id,type:c.length>=3?'parcel':'custom-line',geometry:c.length>=3?'Polygon':'LineString',coords:c,vertexLocks:c.map(()=>false),locked:false,properties:{name:`Reference ${i+1}`,remark:'Migrated reference'},created:new Date().toISOString()})});projects[p.id]=p});if(Object.keys(projects).length)localStorage.setItem(PROJECTS_KEY,JSON.stringify(projects))}
 if(!Object.keys(projects).length)migrateLegacyJobs();
 function saveNow(){if(!project)return;project.updated=new Date().toISOString();projects[project.id]=project;localStorage.setItem(PROJECTS_KEY,JSON.stringify(projects));localStorage.setItem(ACTIVE_KEY,project.id);$('saveStatus').textContent='Saved '+new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});renderSummary()}
 function autosave(){if(!project)return;clearTimeout(saveTimer);$('saveStatus').textContent='Saving…';saveTimer=setTimeout(saveNow,180)}
 const layer=id=>project&&project.layers.find(x=>x.id===id),feature=id=>project&&project.features.find(x=>x.id===id),effectiveLocked=f=>!!(f.locked||layer(f.layerId)?.locked);
 function targetM2(){return arpToM2(+$('A').value||0,+$('R').value||0,+$('P').value||0)}
 function activeDrawLayer(type){const chosen=layer($('drawLayer')?.value);if(chosen&&!chosen.locked)return chosen;const geom=typeInfo[type]?.[1];let l=project.layers.find(x=>!x.locked&&((geom==='Polygon'&&x.kind==='parcel')||(geom==='LineString'&&x.kind==='line')||(geom==='Point'&&x.kind==='point')));return l||project.layers.find(x=>!x.locked)||project.layers[0]}
 function ensureProject(){if(project)return true;openProjectDialog();toast('Create or open a project first');return false}
 function switchProject(id){if(!projects[id])return;project=projects[id];selectedId='';draft=null;editingId='';preview=null;localStorage.setItem(ACTIVE_KEY,id);$('projectChip').textContent=project.name;closeModal('projectModal');renderAll();const c=project.features.flatMap(f=>f.coords||[]);if(c.length)map.fitBounds(L.latLngBounds(c.map(p=>[p[1],p[0]])),{padding:[30,30]});toast('Opened: '+project.name)}
 function createProject(name){const p=defaultProject(name.trim()||'Project '+new Date().toLocaleDateString());projects[p.id]=p;project=p;saveNow();switchProject(p.id)}
 function openProjectDialog(){const box=$('projectChoices');box.innerHTML='';Object.values(projects).sort((a,b)=>(b.updated||'').localeCompare(a.updated||'')).forEach(p=>{const el=document.createElement('div');el.className='listitem';el.innerHTML=`<span class="swatch" style="background:#2fb3a3"></span><div><div class="li-title">${esc(p.name)}</div><div class="li-meta">${p.features.length} features · ${new Date(p.updated).toLocaleString()}</div></div><div class="li-actions"><button class="tiny" data-open="${p.id}">Open</button><button class="tiny" data-delproject="${p.id}">🗑</button></div>`;box.appendChild(el)});$('projectModal').classList.add('show')}
 $('projectChoices').onclick=e=>{const o=e.target.dataset.open,d=e.target.dataset.delproject;if(o)switchProject(o);if(d&&confirm('Delete this project permanently?')){delete projects[d];localStorage.setItem(PROJECTS_KEY,JSON.stringify(projects));if(project?.id===d){project=null;localStorage.removeItem(ACTIVE_KEY)}openProjectDialog()}};
 $('createProjectConfirm').onclick=()=>createProject($('newProjectName').value);$('closeProjectModal').onclick=()=>{if(project)closeModal('projectModal')};

 function geomMeta(f){if(f.geometry==='Polygon')return arpText(ringArea(f.coords));if(f.geometry==='LineString')return lineLength(f.coords).toFixed(2)+' m';return`${f.coords[0][1].toFixed(7)}, ${f.coords[0][0].toFixed(7)}`}
 function renderMap(){featureGroup.clearLayers();featureViews.clear();if(!project)return;project.features.forEach(f=>{const l=layer(f.layerId);if(!l||!l.visible)return;const picked=assembleIds.includes(f.id),color=l.color||'#2fb3a3',latlngs=f.coords.map(p=>[p[1],p[0]]);let v;if(f.geometry==='Polygon')v=L.polygon(latlngs,{color:picked?'#ffb64d':color,weight:f.id===selectedId||picked?4:2,fillColor:color,fillOpacity:f.id===selectedId?.24:.12});else if(f.geometry==='LineString')v=L.polyline(latlngs,{color:picked?'#ffb64d':color,weight:f.id===selectedId||picked?5:3,dashArray:l.kind==='reference'?'7,5':null});else v=L.circleMarker(latlngs[0],{radius:f.id===selectedId||picked?8:6,color:picked?'#ffb64d':'#fff',weight:3,fillColor:color,fillOpacity:1});v.addTo(featureGroup);v.on('click',ev=>{L.DomEvent.stopPropagation(ev);if(mode==='assemble')assembleFeature(f.id);else selectFeature(f.id)});featureViews.set(f.id,v);if(f.geometry==='Polygon'&&f.properties?.name){const c=centroid(f.coords),m=L.marker([c[1],c[0]],{interactive:false,icon:L.divIcon({className:'',html:`<div class="lblbadge" style="color:${color}">${esc(f.properties.name)}</div>`,iconSize:[0,0]})}).addTo(featureGroup);featureViews.set(f.id+'_label',m)}})}
 function selectFeature(id){selectedId=id;const f=feature(id);$('mapStatus').textContent=f?`${f.properties?.name||typeInfo[f.type]?.[0]||'Feature'} · ${geomMeta(f)}${effectiveLocked(f)?' · LOCKED':''}`:'Nothing selected';if(f&&!draft){$('surveyMeasure').textContent=geomMeta(f);$('surveyVertexCount').textContent=`${f.coords.length} vertices`;renderSurveyTable()}renderMap();renderFeatureList()}
 function renderDraft(){draftGroup.clearLayers();if(!draft){$('drawnArea').textContent='0A 0R 0.00P';$('surveyMeasure').textContent='No points';$('surveyVertexCount').textContent='0 vertices';renderSurveyTable();return}const lat=draft.coords.map(p=>[p[1],p[0]]),isPoly=draft.geometry==='Polygon';if(lat.length>1)(isPoly?L.polygon(lat,{color:'#ffb64d',weight:3,fillOpacity:.1}):L.polyline(lat,{color:'#ffb64d',weight:3})).addTo(draftGroup);draft.coords.forEach((p,i)=>{const m=L.marker([p[1],p[0]],{draggable:true,icon:L.divIcon({className:'',html:`<div class="mk ${draft.locks[i]?'locked':''}"></div>`,iconSize:[14,14],iconAnchor:[7,7]})}).addTo(draftGroup);m.on('click',ev=>{L.DomEvent.stopPropagation(ev);draft.locks[i]=!draft.locks[i];renderDraft();toast(draft.locks[i]?'Vertex locked':'Vertex unlocked')});m.on('dragend',ev=>{const q=ev.target.getLatLng(),s=snapDetailed(q);draft.coords[i]=s?[s.ll.lng,s.ll.lat]:[q.lng,q.lat];draft.locks[i]=false;renderDraft()})});const measure=isPoly&&draft.coords.length>=3?arpText(ringArea(draft.coords)):draft.coords.length>1?lineLength(draft.coords).toFixed(2)+' m':'No measurement';$('drawnArea').textContent=measure;$('surveyMeasure').textContent=measure;$('surveyVertexCount').textContent=`${draft.coords.length} vertices`;renderSurveyTable()}
 function renderLayers(){const box=$('layerList'),filter=$('featureFilter'),survey=$('surveyLayer'),edit=$('editFeatureLayer'),draw=$('drawLayer'),oldDraw=draw.value,oldSurvey=survey.value;box.innerHTML='';filter.innerHTML='<option value="all">All layers</option>';survey.innerHTML='';edit.innerHTML='';draw.innerHTML='';if(!project)return;project.layers.forEach(l=>{const count=project.features.filter(f=>f.layerId===l.id).length,el=document.createElement('div');el.className='listitem';el.innerHTML=`<span class="swatch" style="background:${l.color}"></span><div><div class="li-title">${esc(l.name)}</div><div class="li-meta">${count} features · ${esc(l.source||'survey')}</div></div><div class="li-actions"><button class="tiny" data-la="visible" data-id="${l.id}">${l.visible?'👁':'◌'}</button><button class="tiny" data-la="snap" data-id="${l.id}">${l.snap?'🧲':'·'}</button><button class="tiny" data-la="lock" data-id="${l.id}">${l.locked?'🔒':'🔓'}</button><button class="tiny" data-la="export" data-id="${l.id}">${l.export?'⇧':'×'}</button><button class="tiny" data-la="more" data-id="${l.id}">⋮</button></div>`;box.appendChild(el);filter.insertAdjacentHTML('beforeend',`<option value="${l.id}">${esc(l.name)}</option>`);edit.insertAdjacentHTML('beforeend',`<option value="${l.id}">${esc(l.name)}</option>`);if(!l.locked)draw.insertAdjacentHTML('beforeend',`<option value="${l.id}">${esc(l.name)}</option>`);if(l.kind==='point'||!l.locked)survey.insertAdjacentHTML('beforeend',`<option value="${l.id}">${esc(l.name)}</option>`)});if([...draw.options].some(o=>o.value===oldDraw))draw.value=oldDraw;if([...survey.options].some(o=>o.value===oldSurvey))survey.value=oldSurvey;else setSurveyLayerForMethod()}
 function setSurveyLayerForMethod(){if(!project)return;const m=$('surveyMethod').value,k=m==='point'?'point':m==='polygon'?'parcel':'line',l=project.layers.find(x=>!x.locked&&x.kind===k);if(l)$('surveyLayer').value=l.id}
 $('layerList').onclick=e=>{const id=e.target.dataset.id,a=e.target.dataset.la;if(!id||!a)return;const l=layer(id);if(a==='visible')l.visible=!l.visible;if(a==='snap')l.snap=!l.snap;if(a==='lock')l.locked=!l.locked;if(a==='export')l.export=!l.export;if(a==='more'){const act=(prompt('Layer action: rename / colour / delete','rename')||'').toLowerCase();if(act==='rename'){const n=prompt('Layer name',l.name);if(n)l.name=n}else if(act==='colour'||act==='color'){const c=prompt('Layer colour (#RRGGBB)',l.color);if(/^#[0-9a-f]{6}$/i.test(c||''))l.color=c}else if(act==='delete'&&confirm('Delete this layer and all its features?')){project.features=project.features.filter(f=>f.layerId!==id);project.layers=project.layers.filter(x=>x.id!==id)}}autosave();renderAll()};
 function renderFeatureList(){const box=$('featureList');box.innerHTML='';if(!project)return;const fid=$('featureFilter').value||'all';project.features.filter(f=>fid==='all'||f.layerId===fid).forEach(f=>{const l=layer(f.layerId),el=document.createElement('div');el.className='listitem '+(f.id===selectedId?'selected':'');el.innerHTML=`<span class="swatch" style="background:${l?.color||'#aaa'}"></span><div data-select="${f.id}"><div class="li-title">${esc(f.properties?.name||typeInfo[f.type]?.[0]||'Feature')}</div><div class="li-meta">${esc(l?.name)} · ${geomMeta(f)}</div></div><div class="li-actions"><button class="tiny" data-lockfeature="${f.id}">${effectiveLocked(f)?'🔒':'🔓'}</button><button class="tiny" data-info="${f.id}">✎</button></div>`;box.appendChild(el)})}
 $('featureFilter').onchange=renderFeatureList;$('featureList').onclick=e=>{const s=e.target.closest('[data-select]')?.dataset.select,i=e.target.dataset.info,k=e.target.dataset.lockfeature;if(s){selectFeature(s);const f=feature(s),v=featureViews.get(s);if(v&&f.geometry!=='Point')map.fitBounds(v.getBounds(),{padding:[25,25]});else if(v)map.panTo(v.getLatLng())}if(i){selectFeature(i);openFeatureModal()}if(k){const f=feature(k),l=layer(f.layerId);if(l.locked)return toast('Unlock the layer first');f.locked=!f.locked;autosave();renderAll()}};
 function renderCodes(){let codes;try{codes=JSON.parse(localStorage.getItem(CODES_KEY)||'["BP","CP","TP","RL","ROAD","STREAM"]')}catch(e){codes=['BP','CP','TP','RL','ROAD','STREAM']}$('codeList').innerHTML=codes.map(x=>`<option value="${esc(x)}"></option>`).join('')}
 function renderSurveyTable(){const b=$('surveyTable');b.innerHTML='';if(!project)return;const sf=feature(selectedId),rows=draft?.surveySession?draft.coords.map((p,i)=>({p,n:i+1,a:'—'})):sf?sf.coords.map((p,i)=>({p,n:(sf.properties?.number||sf.properties?.name||'F')+'-'+(i+1),a:sf.geometry==='Point'?(sf.properties?.accuracy??'—'):'—'})):project.features.filter(f=>f.geometry==='Point').slice(-100).map(f=>({p:f.coords[0],n:f.properties?.number||f.properties?.name,a:f.properties?.accuracy??'—'}));rows.forEach(x=>{let en=['—','—'];try{en=toSLD(x.p)}catch(e){}b.insertAdjacentHTML('beforeend',`<tr><td>${esc(x.n)}</td><td>${x.p[1].toFixed(7)}</td><td>${x.p[0].toFixed(7)}</td><td>${typeof en[0]==='number'?en[0].toFixed(3):'—'}</td><td>${typeof en[1]==='number'?en[1].toFixed(3):'—'}</td><td>${x.a}</td></tr>`)})}
 function renderSummary(){if(!project)return $('projectSummary').innerHTML='<span>No active project</span>';const n=project.features.length,p=project.features.filter(f=>f.geometry==='Polygon').length,l=project.features.filter(f=>f.geometry==='LineString').length,q=project.features.filter(f=>f.geometry==='Point').length;$('projectSummary').innerHTML=`<span>${project.layers.length} layers</span><span><b>${n}</b> features</span><span>${p} polygons · ${l} lines · ${q} points</span>`}
 function renderAll(){if(!project){$('projectChip').textContent='No project';renderMap();renderLayers();renderFeatureList();return}$('projectChip').textContent=project.name;renderMap();renderDraft();renderLayers();renderFeatureList();renderSurveyTable();renderCodes();renderSummary();$('targetArea').textContent=arpText(targetM2())}

 function snapDetailed(ll){if(!project)return null;const cp=map.latLngToContainerPoint(ll);let best=null,bd=20;project.features.forEach(f=>{const l=layer(f.layerId);if(!l?.visible||!l.snap)return;f.coords.forEach((p,i)=>{const x=map.latLngToContainerPoint([p[1],p[0]]),d=Math.hypot(x.x-cp.x,x.y-cp.y);if(d<bd){bd=d;best={ll:L.latLng(p[1],p[0]),featureId:f.id,kind:'vertex',index:i,segment:Math.max(0,i-1),t:1}}});if(f.geometry==='Point'||f.coords.length<2)return;const count=f.geometry==='Polygon'?f.coords.length:f.coords.length-1;for(let i=0;i<count;i++){const p=f.coords[i],q=f.coords[(i+1)%f.coords.length],a=map.latLngToContainerPoint([p[1],p[0]]),b=map.latLngToContainerPoint([q[1],q[0]]),dx=b.x-a.x,dy=b.y-a.y,l2=dx*dx+dy*dy||1,t=Math.max(0,Math.min(1,((cp.x-a.x)*dx+(cp.y-a.y)*dy)/l2)),x=a.x+dx*t,y=a.y+dy*t,d=Math.hypot(x-cp.x,y-cp.y);if(d<bd){bd=d;best={ll:map.containerPointToLatLng([x,y]),featureId:f.id,kind:'nearest',segment:i,t}}}});return best}
 function newDraft(type){const t=typeInfo[type]||typeInfo.parcel;draft={type,geometry:t[1],coords:[],locks:[],layerId:activeDrawLayer(type).id,properties:{name:$('featureName').value.trim(),remark:$('featureRemark').value.trim()}};editingId='';renderDraft()}
 function addDraftPoint(ll){const s=snapDetailed(ll),p=s?s.ll:ll;draft.coords.push([p.lng,p.lat]);draft.locks.push($('lockNewVertices').checked);renderDraft();if(s)toast(`${s.kind==='vertex'?'Endpoint/vertex':'Nearest'} snap${$('lockNewVertices').checked?' · locked':''}`)}
 function beginDraw(){if(!ensureProject())return;newDraft($('featureType').value);mode='draw';$('drawBtn').classList.add('active');$('mapStatus').textContent='Tap map to add points. First tap may snap exactly.'}
 function clearDraft(){draft=null;editingId='';mode='select';draftGroup.clearLayers();$('drawBtn').classList.remove('active');renderDraft()}
 function addOrReplace(f){if(editingId){const i=project.features.findIndex(x=>x.id===editingId);f.id=editingId;project.features[i]=f}else project.features.push(f);selectedId=f.id;clearDraft();autosave();renderAll()}
 function finishDraft(){if(!draft)return toast('Start drawing first');const min=draft.geometry==='Polygon'?3:draft.geometry==='LineString'?2:1;if(draft.coords.length<min)return toast(`Need at least ${min} point(s)`);draft.properties.name=$('featureName').value.trim()||draft.properties.name||typeInfo[draft.type][0];draft.properties.remark=$('featureRemark').value.trim();const f={id:editingId||uid('feature'),layerId:draft.layerId,type:draft.type,geometry:draft.geometry,coords:draft.coords.map(x=>x.slice()),vertexLocks:draft.locks.slice(),locked:false,properties:{...draft.properties},created:new Date().toISOString()};if(f.geometry==='Polygon'&&$('autoFit').checked&&targetM2()>0){const fit=fitCoords(f.coords,f.vertexLocks,targetM2());if(!fit.ok)return toast(fit.error);f.coords=fit.coords;showFitPreview(f,!!editingId);return}addOrReplace(f)}
 function fitCoords(coords,locks,target){const cur=ringArea(coords),fixed=coords.filter((_,i)=>locks[i]);if(fixed.length===coords.length)return Math.abs(cur-target)<.05?{ok:true,coords}:{ok:false,error:'All vertices are snapped/locked'};const c=centroid(fixed.length?fixed:coords),lat=c[1],mlon=111320*Math.cos(lat*Math.PI/180),mlat=110540,at=k=>coords.map((p,i)=>locks[i]?p.slice():[c[0]+((p[0]-c[0])*mlon*k)/mlon,c[1]+((p[1]-c[1])*mlat*k)/mlat]);let lo=0,hi=1,a0=ringArea(at(0)),ah=ringArea(at(1));if(target<a0-.05)return{ok:false,error:'Target is too small while snapped points stay fixed'};while(ah<target&&hi<1024){hi*=2;ah=ringArea(at(hi))}if(ah<target)return{ok:false,error:'Target cannot be reached'};for(let i=0;i<70;i++){const m=(lo+hi)/2;if(ringArea(at(m))<target)lo=m;else hi=m}return{ok:true,coords:at((lo+hi)/2)}}
 function showFitPreview(f,wasEdit){preview={kind:'fit',feature:f,wasEdit};previewGroup.clearLayers();L.polygon(f.coords.map(p=>[p[1],p[0]]),{color:'#ffb64d',weight:4,fillOpacity:.23}).addTo(previewGroup);$('previewTitle').textContent='Auto Fit Preview';$('previewText').textContent=`Target ${arpText(targetM2())} · Result ${arpText(ringArea(f.coords))}. Red snapped vertices remain unchanged.`;$('splitOptions').classList.add('hidden');$('keepRemainder').classList.add('hidden');$('keepBoth').classList.add('hidden');$('previewModal').classList.add('show')}
 function manualFit(){if(draft&&draft.geometry==='Polygon'){const r=fitCoords(draft.coords,draft.locks,targetM2());if(!r.ok)return toast(r.error);draft.coords=r.coords;renderDraft();toast('Draft fitted; locked vertices unchanged');return}const f=feature(selectedId);if(!f||f.geometry!=='Polygon')return toast('Select a polygon or draw one first');if(effectiveLocked(f))return toast('Feature/layer is locked');const r=fitCoords(f.coords,f.vertexLocks||f.coords.map(()=>false),targetM2());if(!r.ok)return toast(r.error);showFitPreview({...f,coords:r.coords},true)}

 function tracePath(f,s,e){const c=f.coords,n=c.length,closed=f.geometry==='Polygon';if(!closed){const a=s.segment+s.t,b=e.segment+e.t,out=[ [s.ll.lng,s.ll.lat] ];if(a<=b){for(let i=s.segment+1;i<=e.segment;i++)out.push(c[i].slice())}else{for(let i=s.segment;i>e.segment;i--)out.push(c[i].slice())}out.push([e.ll.lng,e.ll.lat]);return out}const forward=[[s.ll.lng,s.ll.lat]];let seg=s.segment;while(seg!==e.segment){forward.push(c[(seg+1)%n].slice());seg=(seg+1)%n;if(forward.length>n+2)break}forward.push([e.ll.lng,e.ll.lat]);const reverse=[[s.ll.lng,s.ll.lat]];seg=s.segment;while(seg!==e.segment){reverse.push(c[seg].slice());seg=(seg-1+n)%n;if(reverse.length>n+2)break}reverse.push([e.ll.lng,e.ll.lat]);return lineLength(forward)<=lineLength(reverse)?forward:reverse}
 function beginTrace(){if(!ensureProject())return;if(!draft)newDraft($('featureType').value);mode='traceStart';traceStart=null;$('mapStatus').textContent='Trace: tap start point on an existing visible snap layer'}
 function traceClick(ll){const s=snapDetailed(ll);if(!s)return toast('Tap close to an existing boundary');if(mode==='traceStart'){traceStart=s;mode='traceEnd';$('mapStatus').textContent='Trace: tap end point on the same feature';return toast('Trace start fixed')}if(s.featureId!==traceStart.featureId)return toast('End point must be on the same feature');const path=tracePath(feature(s.featureId),traceStart,s);path.forEach((p,i)=>{if(i===0&&draft.coords.length&&distance(draft.coords.at(-1),p)<.02)return;draft.coords.push(p);draft.locks.push($('lockNewVertices').checked)});mode='draw';traceStart=null;renderDraft();toast('Existing boundary copied; continue drawing')}

 function areaXY(q){let s=0;for(let i=0;i<q.length;i++){const a=q[i],b=q[(i+1)%q.length];s+=a[0]*b[1]-b[0]*a[1]}return Math.abs(s)/2}
 function clipHalf(q,a,b,pos){const out=[],side=p=>(b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]),inside=p=>pos?side(p)>=-1e-8:side(p)<=1e-8;for(let i=0;i<q.length;i++){const p=q[i],r=q[(i+1)%q.length],ip=inside(p),ir=inside(r);if(ip)out.push(p);if(ip!==ir){const sp=side(p),sr=side(r),t=sp/(sp-sr);out.push([p[0]+(r[0]-p[0])*t,p[1]+(r[1]-p[1])*t])}}return out}
 function startSplit(kind){const f=feature(selectedId);if(!f||f.geometry!=='Polygon')return toast('Select an existing polygon first');if(effectiveLocked(f))return toast('Unlock the feature and layer first');if(targetM2()<=0||targetM2()>=ringArea(f.coords))return toast('Target area must be smaller than selected polygon');mode=kind==='parallel'?'splitParallel':'splitRotate';picks=[];$('mapStatus').textContent=kind==='parallel'?'Tap two points for parallel cut direction':'Tap pivot point, then direction point';toast($('mapStatus').textContent)}
 function calculateSplit(kind,side){const f=feature(selectedId),q=f.coords.map(toSLD),tgt=targetM2(),positive=side>0;let target,remainder,params;if(kind==='parallel'){let a=toSLD([picks[0].lng,picks[0].lat]),b=toSLD([picks[1].lng,picks[1].lat]),dx=b[0]-a[0],dy=b[1]-a[1],len=Math.hypot(dx,dy);if(len<.01)throw Error('Cut points are too close');const nx=-dy/len,ny=dx/len,pr=q.map(p=>p[0]*nx+p[1]*ny),base=a[0]*nx+a[1]*ny;let lo=Math.min(...pr)-base-1,hi=Math.max(...pr)-base+1;for(let i=0;i<75;i++){const d=(lo+hi)/2,A=[a[0]+nx*d,a[1]+ny*d],B=[b[0]+nx*d,b[1]+ny*d],ar=areaXY(clipHalf(q,A,B,positive));if(positive?(ar>tgt):(ar<tgt))lo=d;else hi=d}const d=(lo+hi)/2,A=[a[0]+nx*d,a[1]+ny*d],B=[b[0]+nx*d,b[1]+ny*d];target=clipHalf(q,A,B,positive);remainder=clipHalf(q,A,B,!positive);params={kind,side}}else{const p=toSLD([picks[0].lng,picks[0].lat]),d=toSLD([picks[1].lng,picks[1].lat]),base=Math.atan2(d[1]-p[1],d[0]-p[0]);let best={e:Infinity,t:0},cross=null,prev=null;for(let i=0;i<=1440;i++){const th=Math.PI*i/1440,b=[p[0]+Math.cos(base+th),p[1]+Math.sin(base+th)],v=areaXY(clipHalf(q,p,b,positive))-tgt;if(Math.abs(v)<best.e)best={e:Math.abs(v),t:th};if(prev&&v*prev.v<=0){cross=[prev.t,th];break}prev={t:th,v}}let th=best.t;if(cross){let[lo,hi]=cross,vlo=areaXY(clipHalf(q,p,[p[0]+Math.cos(base+lo),p[1]+Math.sin(base+lo)],positive))-tgt;for(let i=0;i<70;i++){const m=(lo+hi)/2,v=areaXY(clipHalf(q,p,[p[0]+Math.cos(base+m),p[1]+Math.sin(base+m)],positive))-tgt;if(v*vlo<=0)hi=m;else{lo=m;vlo=v}}th=(lo+hi)/2}const b=[p[0]+Math.cos(base+th),p[1]+Math.sin(base+th)];target=clipHalf(q,p,b,positive);remainder=clipHalf(q,p,b,!positive);if(Math.abs(areaXY(target)-tgt)>.3)throw Error('Choose another pivot; target cannot be reached');params={kind,side}}
  if(target.length<3||remainder.length<3)throw Error('Cut does not cross polygon');return{target:target.map(fromSLD),remainder:remainder.map(fromSLD),params,sourceId:f.id}}
 function showSplit(kind,side=1){try{const r=calculateSplit(kind,side);preview={kind:'split',...r};previewGroup.clearLayers();L.polygon(r.target.map(p=>[p[1],p[0]]),{color:'#ffb64d',weight:4,fillOpacity:.3}).addTo(previewGroup);L.polygon(r.remainder.map(p=>[p[1],p[0]]),{color:'#bd8cff',weight:3,fillOpacity:.14}).addTo(previewGroup);$('previewTitle').textContent='Area Split Preview';$('previewText').textContent=`Target (amber): ${arpText(ringArea(r.target))} · Remainder (purple): ${arpText(ringArea(r.remainder))}`;$('splitOptions').classList.remove('hidden');$('keepRemainder').classList.remove('hidden');$('keepBoth').classList.remove('hidden');$('acceptPreview').textContent='Keep Target';$('previewModal').classList.add('show')}catch(e){mode='select';toast(e.message)}}
 function acceptSplit(which){const s=feature(preview.sourceId),idx=project.features.findIndex(f=>f.id===s.id);project.features.splice(idx,1);const mk=(coords,suf)=>({id:uid('feature'),layerId:s.layerId,type:s.type,geometry:'Polygon',coords,vertexLocks:coords.map(()=>false),locked:false,properties:{...s.properties,name:(s.properties.name||'Parcel')+'-'+suf},created:new Date().toISOString()});if(which==='target'||which==='both')project.features.push(mk(preview.target,'T'));if(which==='remainder'||which==='both')project.features.push(mk(preview.remainder,'R'));previewGroup.clearLayers();closeModal('previewModal');preview=null;mode='select';autosave();renderAll();toast(which==='both'?'Both split parts kept':which==='target'?'Target area kept':'Remainder kept')}
 function cancelPreview(){previewGroup.clearLayers();closeModal('previewModal');preview=null;mode='select';renderMap();renderDraft()}
 $('acceptPreview').onclick=()=>{if(preview?.kind==='split')return acceptSplit('target');if(preview?.kind==='fit'){addOrReplace(preview.feature);previewGroup.clearLayers();closeModal('previewModal');preview=null;toast('Auto fit accepted')}};$('keepRemainder').onclick=()=>acceptSplit('remainder');$('keepBoth').onclick=()=>acceptSplit('both');$('swapSideBtn').onclick=()=>{if(preview?.kind==='split')showSplit(preview.params.kind,-preview.params.side)};$('cancelPreview').onclick=cancelPreview;

 map.on('click',e=>{if(!project)return openProjectDialog();if(mode==='draw')return addDraftPoint(e.latlng);if(mode==='traceStart'||mode==='traceEnd')return traceClick(e.latlng);if(mode==='surveyTap'){const s=snapDetailed(e.latlng),p=s?s.ll:e.latlng;addSurveyCoordinate([p.lng,p.lat],null);if($('surveyMethod').value==='point')mode='select';else mode='surveyTap';return}if(mode==='splitParallel'||mode==='splitRotate'){picks.push(e.latlng);if(picks.length===2)showSplit(mode==='splitParallel'?'parallel':'rotate',1);return}if(mode==='select'){const s=snapDetailed(e.latlng);if(s)selectFeature(s.featureId);else selectFeature('')}});
 $('drawBtn').onclick=beginDraw;$('finishBtn').onclick=finishDraft;$('cancelDrawBtn').onclick=clearDraft;$('selectBtn').onclick=()=>{mode='select';toast('Select mode')};$('traceBtn').onclick=beginTrace;$('fitBtn').onclick=manualFit;$('parallelBtn').onclick=()=>startSplit('parallel');$('rotateBtn').onclick=()=>startSplit('rotate');$('undoFab').onclick=()=>{if(draft?.coords.length){draft.coords.pop();draft.locks.pop();renderDraft()}else toast('Nothing to undo')};
 $('editBtn').onclick=()=>{const f=feature(selectedId);if(!f)return toast('Select a feature');if(effectiveLocked(f))return toast('Feature/layer is locked');draft={type:f.type,geometry:f.geometry,coords:f.coords.map(x=>x.slice()),locks:(f.vertexLocks||f.coords.map(()=>false)).slice(),layerId:f.layerId,properties:{...f.properties}};editingId=f.id;mode='draw';$('featureType').value=f.type;$('featureName').value=f.properties?.name||'';$('featureRemark').value=f.properties?.remark||'';renderDraft();toast('Geometry edit mode')};
 function openFeatureModal(){const f=feature(selectedId);if(!f)return;$('editFeatureName').value=f.properties?.name||'';$('editFeatureRemark').value=f.properties?.remark||'';$('editFeatureLayer').value=f.layerId;$('editFeatureLock').checked=!!f.locked;$('editFeatureInfo').textContent=`${typeInfo[f.type]?.[0]||f.type} · ${geomMeta(f)} · ${f.coords.length} point(s)`;$('featureModal').classList.add('show')}
 $('saveFeatureEdit').onclick=()=>{const f=feature(selectedId);f.properties.name=$('editFeatureName').value.trim();f.properties.remark=$('editFeatureRemark').value.trim();f.layerId=$('editFeatureLayer').value;f.locked=$('editFeatureLock').checked;autosave();closeModal('featureModal');renderAll()};$('deleteFeature').onclick=()=>{const f=feature(selectedId);if(!f)return;if(effectiveLocked(f))return toast('Unlock before deleting');if(confirm('Delete selected feature?')){project.features=project.features.filter(x=>x.id!==selectedId);selectedId='';autosave();closeModal('featureModal');renderAll()}};$('closeFeatureModal').onclick=()=>closeModal('featureModal');

 function secure(){return window.isSecureContext||location.hostname==='localhost'||location.hostname==='127.0.0.1'}
 function locate(cb,center=false){if(!secure())return toast('GPS requires the HTTPS GitHub Pages link');navigator.geolocation.getCurrentPosition(p=>{lastGps=p;showGps(p,center);$('gpsStatus').textContent=`±${p.coords.accuracy.toFixed(1)} m · ${new Date(p.timestamp).toLocaleTimeString()}`;if(cb)cb(p)},e=>toast('GPS: '+e.message),{enableHighAccuracy:true,timeout:20000,maximumAge:0})}
 function showGps(p,center){gpsGroup.clearLayers();const ll=[p.coords.latitude,p.coords.longitude];L.circle(ll,{radius:p.coords.accuracy,color:'#6eb7ff',weight:1,fillOpacity:.1}).addTo(gpsGroup);L.marker(ll,{icon:L.divIcon({className:'',html:'<div class="gpspulse"></div>',iconSize:[18,18],iconAnchor:[9,9]})}).addTo(gpsGroup);if(center)map.setView(ll,19)}
 $('gpsFab').onclick=()=>locate(null,true);
 function nextPointNo(){const nums=project.features.filter(f=>f.geometry==='Point').map(f=>parseInt(f.properties?.number,10)).filter(Number.isFinite);return String((nums.length?Math.max(...nums):0)+1)}
 function saveSurveyPoint(c,p){if(!ensureProject())return;const code=$('pointCode').value.trim(),num=$('pointNo').value.trim()||nextPointNo(),f={id:uid('feature'),layerId:$('surveyLayer').value||activeDrawLayer('point').id,type:'point',geometry:'Point',coords:[c],vertexLocks:[false],locked:false,properties:{name:num,number:num,code,remark:$('pointRemark').value.trim(),accuracy:p?+p.coords.accuracy.toFixed(3):null,source:p?'GPS':'map'},created:new Date().toISOString()};project.features.push(f);selectedId=f.id;$('pointNo').value=String((parseInt(num,10)||0)+1);mode='select';autosave();renderAll();toast(`Point ${num} saved`)}
 function surveySpec(method=$('surveyMethod').value){if(method==='line')return{type:'boundary',geometry:'LineString',min:2,max:2};if(method==='polyline')return{type:'custom-line',geometry:'LineString',min:2,max:Infinity};if(method==='polygon')return{type:'parcel',geometry:'Polygon',min:3,max:Infinity};return{type:'point',geometry:'Point',min:1,max:1}}
 function ensureSurveyDraft(method=$('surveyMethod').value){const s=surveySpec(method);if(s.geometry==='Point')return null;if(draft&&draft.surveySession&&draft.geometry===s.geometry&&draft.type===s.type)return draft;if(draft&&draft.coords.length&&!confirm('Clear the current unfinished geometry and start this survey session?'))return null;draft={type:s.type,geometry:s.geometry,coords:[],locks:[],layerId:$('surveyLayer').value||activeDrawLayer(s.type).id,properties:{name:$('pointNo').value.trim()||s.type,code:$('pointCode').value.trim(),remark:$('pointRemark').value.trim()},surveySession:true};editingId='';renderDraft();return draft}
 function addSurveyCoordinate(c,p=null){const method=$('surveyMethod').value,s=surveySpec(method);if(method==='point')return saveSurveyPoint(c,p);const d=ensureSurveyDraft(method);if(!d)return;if(Number.isFinite(s.max)&&d.coords.length>=s.max)return toast('Line already has 2 points — Finish or use Polyline');d.coords.push(c);d.locks.push($('lockNewVertices').checked);renderDraft();if(s.max===2&&d.coords.length===2)toast('Line has 2 points — press Finish Geometry')}
 function finishSurveyGeometry(){if(!draft?.surveySession)return toast('No active survey geometry');const s=surveySpec(),n=draft.coords.length;if(n<s.min)return toast(`Need at least ${s.min} point(s)`);if(Number.isFinite(s.max)&&n>s.max)return toast(`Line method accepts exactly ${s.max} points; use Polyline`);const num=$('pointNo').value.trim()||`${typeInfo[draft.type]?.[0]} ${project.features.length+1}`,f={id:uid('feature'),layerId:$('surveyLayer').value||draft.layerId,type:draft.type,geometry:draft.geometry,coords:draft.coords.map(x=>x.slice()),vertexLocks:draft.locks.slice(),locked:false,properties:{name:num,number:num,code:$('pointCode').value.trim(),remark:$('pointRemark').value.trim(),source:'survey'},created:new Date().toISOString()};project.features.push(f);selectedId=f.id;clearDraft();autosave();renderAll();selectFeature(f.id);toast(`${f.geometry} saved · ${geomMeta(f)}`)}
 $('gpsPointBtn').onclick=()=>locate(p=>addSurveyCoordinate([p.coords.longitude,p.coords.latitude],p),true);$('tapPointBtn').onclick=()=>{if(!ensureProject())return;mode='surveyTap';toast('Tap map to add the next survey position')};
 $('surveyMethod').dataset.prev=$('surveyMethod').value;$('surveyMethod').onchange=()=>{const el=$('surveyMethod');if(draft?.surveySession&&draft.coords.length){if(!confirm('Changing method will clear the current survey session. Continue?')){el.value=el.dataset.prev;return}clearDraft()}el.dataset.prev=el.value;setSurveyLayerForMethod();renderDraft()};
 $('surveyFinishBtn').onclick=finishSurveyGeometry;$('surveyUndoBtn').onclick=()=>{if(draft?.surveySession&&draft.coords.length){draft.coords.pop();draft.locks.pop();renderDraft()}else toast('No survey point to undo')};$('surveyClearBtn').onclick=()=>{if(draft?.surveySession)clearDraft();toast('Survey session cleared')};$('surveyToMapBtn').onclick=()=>{if(!selectedId)return toast('Finish or select a polygon first');switchTab('mapPage');toast('Selected feature is ready for Auto Fit or Area Split')};
 function rebuildAssembly(){assembleCoords=[];let gapMax=0;assembleIds.forEach(id=>{const f=feature(id);if(!f)return;let part=f.geometry==='Point'?[f.coords[0].slice()]:f.coords.map(x=>x.slice());if(assembleCoords.length&&part.length){const end=assembleCoords.at(-1),d1=distance(end,part[0]),d2=distance(end,part.at(-1));if(d2<d1)part.reverse();gapMax=Math.max(gapMax,Math.min(d1,d2));if(distance(end,part[0])<.05)part.shift()}assembleCoords.push(...part)});previewGroup.clearLayers();if(assembleCoords.length>1){const lat=assembleCoords.map(p=>[p[1],p[0]]);($('joinOutput').value==='polygon'&&assembleCoords.length>=3?L.polygon(lat,{color:'#ffb64d',weight:4,fillOpacity:.16}):L.polyline(lat,{color:'#ffb64d',weight:4})).addTo(previewGroup)}const measure=$('joinOutput').value==='polygon'&&assembleCoords.length>=3?arpText(ringArea(assembleCoords)):lineLength(assembleCoords).toFixed(2)+' m';$('assembleStatus').textContent=`${assembleIds.length} selected · ${assembleCoords.length} vertices · ${measure}${gapMax>.25?' · gap '+gapMax.toFixed(2)+'m':''}`;renderMap()}
 function assembleFeature(id){const f=feature(id);if(!f||!['Point','LineString'].includes(f.geometry))return toast('Select survey points or boundary lines only');const i=assembleIds.indexOf(id);if(i>=0)assembleIds.splice(i,1);else assembleIds.push(id);rebuildAssembly()}
 $('assembleBtn').onclick=()=>{if(!ensureProject())return;assembleIds=[];assembleCoords=[];mode='assemble';rebuildAssembly();toast('Tap required points/lines in joining order')};$('joinOutput').onchange=rebuildAssembly;$('assembleClearBtn').onclick=()=>{assembleIds=[];assembleCoords=[];previewGroup.clearLayers();mode='select';$('assembleStatus').textContent='Selection cleared';renderMap()};$('assembleFinishBtn').onclick=()=>{const poly=$('joinOutput').value==='polygon',min=poly?3:2;if(assembleCoords.length<min)return toast(`Select enough points/lines (${min}+ vertices)`);const num=$('pointNo').value.trim()||(poly?'Joined Parcel':'Joined Boundary'),dest=project.layers.find(x=>!x.locked&&x.kind===(poly?'parcel':'line'))||layer($('surveyLayer').value),f={id:uid('feature'),layerId:dest.id,type:poly?'parcel':'boundary',geometry:poly?'Polygon':'LineString',coords:assembleCoords.map(x=>x.slice()),vertexLocks:assembleCoords.map(()=>false),locked:false,properties:{name:num,number:num,code:$('pointCode').value.trim(),remark:$('pointRemark').value.trim(),source:'joined survey features'},created:new Date().toISOString()};project.features.push(f);selectedId=f.id;assembleIds=[];assembleCoords=[];previewGroup.clearLayers();mode='select';autosave();renderAll();selectFeature(f.id);toast(`${poly?'Polygon':'Polyline'} joined; source features kept`)};
 $('addCodeBtn').onclick=()=>{const v=prompt('New point/feature code',$('pointCode').value||'');if(!v)return;let c;try{c=JSON.parse(localStorage.getItem(CODES_KEY)||'["BP","CP","TP","RL","ROAD","STREAM"]')}catch(e){c=['BP','CP','TP','RL','ROAD','STREAM']}if(!c.includes(v.trim()))c.push(v.trim());localStorage.setItem(CODES_KEY,JSON.stringify(c));$('pointCode').value=v.trim();renderCodes()};
 function walkAdd(p,force){lastGps=p;showGps(p,false);const max=+$('maxAccuracy').value||5;if(p.coords.accuracy>max&&!force){$('walkStatus').textContent=`Skipped ±${p.coords.accuracy.toFixed(1)}m`;return}const c=[p.coords.longitude,p.coords.latitude],min=+$('walkDistance').value||1;if(!force&&draft.coords.length&&distance(draft.coords.at(-1),c)<min)return;draft.coords.push(c);draft.locks.push($('lockNewVertices').checked);renderDraft();$('walkStatus').textContent=`Recording · ${draft.coords.length} pts · ±${p.coords.accuracy.toFixed(1)}m`}
 $('walkStartBtn').onclick=()=>{if(!ensureProject()||!secure())return toast('GPS walk requires HTTPS');if(walkId!==null)return;$('surveyMethod').value='polygon';$('surveyMethod').dataset.prev='polygon';setSurveyLayerForMethod();if(!ensureSurveyDraft('polygon'))return;mode='walk';walkId=navigator.geolocation.watchPosition(p=>walkAdd(p,false),e=>toast('GPS: '+e.message),{enableHighAccuracy:true,timeout:20000,maximumAge:0});$('walkStatus').textContent='Recording…';toast('GPS boundary walk started')};$('walkRecordBtn').onclick=()=>{if(lastGps&&draft)walkAdd(lastGps,true);else locate(p=>{if(!draft){$('surveyMethod').value='polygon';setSurveyLayerForMethod();ensureSurveyDraft('polygon')}walkAdd(p,true)})};$('walkStopBtn').onclick=()=>{if(walkId!==null){navigator.geolocation.clearWatch(walkId);walkId=null}$('walkStatus').textContent=`Stopped · ${draft?.coords.length||0} points`;if(draft?.coords.length>=3)finishSurveyGeometry();else toast('Need at least 3 positions')};

 function addLayer(name,kind='line',color='#bd8cff',source='survey'){const l={id:uid('lyr'),name,kind,color,visible:true,locked:false,snap:true,export:true,source};project.layers.push(l);return l}
 $('addLayerBtn').onclick=()=>{if(!ensureProject())return;const n=prompt('New layer name','Additional Features');if(!n)return;const kind=prompt('Layer kind: parcel, line, point, reference','line')||'line',c=prompt('Colour (#RRGGBB)','#bd8cff')||'#bd8cff';addLayer(n,kind,/^#[0-9a-f]{6}$/i.test(c)?c:'#bd8cff');autosave();renderAll()};
 function parseKML(t){const d=new DOMParser().parseFromString(t,'application/xml');if(d.querySelector('parsererror'))throw Error('Invalid KML');const out=[];d.querySelectorAll('Placemark').forEach(pm=>{const name=pm.querySelector('name')?.textContent||'',remark=pm.querySelector('description')?.textContent||'';['Polygon','LineString','Point'].forEach(g=>{pm.querySelectorAll(g).forEach(el=>{const ce=el.querySelector('coordinates');if(!ce)return;let c=ce.textContent.trim().split(/\s+/).map(x=>x.split(',')).filter(x=>Number.isFinite(+x[0])&&Number.isFinite(+x[1])).map(x=>[+x[0],+x[1]]);if(g==='Polygon'&&c.length>1&&distance(c[0],c.at(-1))<.01)c.pop();if(c.length)out.push({geometry:g,coords:c,name,remark})})})});return out}
 function importKML(t,name){const a=parseKML(t);if(!a.length)throw Error('No supported KML geometry');const l=addLayer(name.replace(/\.kml$/i,''),'reference','#bd8cff','KML');a.forEach((x,i)=>project.features.push({id:uid('feature'),layerId:l.id,type:x.geometry==='Polygon'?'parcel':x.geometry==='Point'?'point':'custom-line',geometry:x.geometry,coords:x.coords,vertexLocks:x.coords.map(()=>false),locked:false,properties:{name:x.name||`${l.name} ${i+1}`,remark:x.remark},created:new Date().toISOString()}));autosave();renderAll();map.fitBounds(L.latLngBounds(a.flatMap(x=>x.coords).map(p=>[p[1],p[0]])),{padding:[25,25]});toast(`${a.length} KML feature(s) imported`)}
 function dxfPairs(t){const a=t.replace(/\r/g,'').split('\n'),p=[];for(let i=0;i+1<a.length;i+=2)p.push([a[i].trim(),a[i+1].trim()]);return p}
 function parseDXF(t){const p=dxfPairs(t),out=[];for(let i=0;i<p.length;i++){if(p[i][0]!=='0')continue;const typ=p[i][1];if(typ==='LWPOLYLINE'){let c=[],x=null,l='0',closed=false;i++;for(;i<p.length&&p[i][0]!=='0';i++){if(p[i][0]==='8')l=p[i][1];if(p[i][0]==='70')closed=(+p[i][1]&1)!==0;if(p[i][0]==='10')x=+p[i][1];if(p[i][0]==='20'&&x!==null){c.push([x,+p[i][1]]);x=null}}i--;if(c.length>=2)out.push({layer:l,geometry:closed?'Polygon':'LineString',xy:c})}else if(typ==='POLYLINE'){let c=[],l='0',closed=false,header=true;i++;for(;i<p.length;i++){if(header&&p[i][0]==='8')l=p[i][1];if(header&&p[i][0]==='70')closed=(+p[i][1]&1)!==0;if(p[i][0]==='0'&&p[i][1]==='SEQEND')break;if(p[i][0]==='0'&&p[i][1]==='VERTEX'){header=false;let x,y;i++;for(;i<p.length&&p[i][0]!=='0';i++){if(p[i][0]==='10')x=+p[i][1];if(p[i][0]==='20')y=+p[i][1]}i--;if(Number.isFinite(x)&&Number.isFinite(y))c.push([x,y])}}if(c.length>=2)out.push({layer:l,geometry:closed?'Polygon':'LineString',xy:c})}else if(typ==='LINE'||typ==='POINT'){let l='0',x,y,x2,y2;i++;for(;i<p.length&&p[i][0]!=='0';i++){if(p[i][0]==='8')l=p[i][1];if(p[i][0]==='10')x=+p[i][1];if(p[i][0]==='20')y=+p[i][1];if(p[i][0]==='11')x2=+p[i][1];if(p[i][0]==='21')y2=+p[i][1]}i--;if(Number.isFinite(x)&&Number.isFinite(y))out.push({layer:l,geometry:typ==='POINT'?'Point':'LineString',xy:typ==='POINT'?[[x,y]]:[[x,y],[x2,y2]]})}}return out}
 function importDXF(t,name){if(!window.proj4)throw Error('SLD99 converter unavailable');const a=parseDXF(t);if(!a.length)throw Error('No supported DXF geometry');const lm={};a.forEach(x=>{if(!lm[x.layer])lm[x.layer]=addLayer(x.layer||name.replace(/\.dxf$/i,''),'reference','#bd8cff','DXF · SLD99');const c=x.xy.map(fromSLD);project.features.push({id:uid('feature'),layerId:lm[x.layer].id,type:x.geometry==='Polygon'?'parcel':x.geometry==='Point'?'point':'custom-line',geometry:x.geometry,coords:c,vertexLocks:c.map(()=>false),locked:false,properties:{name:x.layer||'DXF feature',remark:'Imported '+name},created:new Date().toISOString()})});autosave();renderAll();const c=a.flatMap(x=>x.xy).map(fromSLD);map.fitBounds(L.latLngBounds(c.map(p=>[p[1],p[0]])),{padding:[25,25]});toast(`${a.length} DXF feature(s), ${Object.keys(lm).length} layer(s) imported`)}
 function chooseFile(m,accept){fileMode=m;$('fileInput').accept=accept;$('fileInput').value='';$('fileInput').click()}
 $('importKmlBtn').onclick=()=>{if(ensureProject())chooseFile('kml','.kml')};$('importDxfBtn').onclick=()=>{if(ensureProject())chooseFile('dxf','.dxf')};$('projectImportBtn').onclick=()=>chooseFile('project','.json,.fieldsketch');
 $('fileInput').onchange=async()=>{const f=$('fileInput').files[0];if(!f)return;try{const t=await f.text();if(fileMode==='kml')importKML(t,f.name);else if(fileMode==='dxf')importDXF(t,f.name);else{const p=JSON.parse(t);if(p.schema!=='fieldsketch-project'||!Array.isArray(p.layers)||!Array.isArray(p.features))throw Error('Not a FieldSketch project');p.id=uid('project');p.name=(p.name||'Imported Project')+' (Imported)';projects[p.id]=p;localStorage.setItem(PROJECTS_KEY,JSON.stringify(projects));switchProject(p.id);saveNow();toast('Complete project imported')}}catch(e){toast('Import failed: '+e.message)}};
 function exportFeatures(){return project.features.filter(f=>{const l=layer(f.layerId);return l?.visible&&l.export})}
 function kmlText(){let folders='';project.layers.filter(l=>l.visible&&l.export).forEach(l=>{let body='';project.features.filter(f=>f.layerId===l.id).forEach(f=>{const n=xml(f.properties?.name||typeInfo[f.type]?.[0]),r=xml(f.properties?.remark||''),style=`<Style><LineStyle><color>ff${l.color.slice(5,7)}${l.color.slice(3,5)}${l.color.slice(1,3)}</color><width>3</width></LineStyle><PolyStyle><color>44${l.color.slice(5,7)}${l.color.slice(3,5)}${l.color.slice(1,3)}</color></PolyStyle></Style>`,desc=`<description>${r}</description><ExtendedData><Data name="layer"><value>${xml(l.name)}</value></Data><Data name="type"><value>${xml(f.type)}</value></Data><Data name="locked"><value>${f.locked}</value></Data></ExtendedData>`;if(f.geometry==='Point'){const p=f.coords[0];body+=`<Placemark><name>${n}</name>${style}${desc}<Point><coordinates>${p[0]},${p[1]},0</coordinates></Point></Placemark>`}else{let c=f.coords.slice();if(f.geometry==='Polygon')c=c.concat([c[0]]);const cs=c.map(p=>`${p[0].toFixed(9)},${p[1].toFixed(9)},0`).join(' ');body+=`<Placemark><name>${n}</name>${style}${desc}<${f.geometry}>${f.geometry==='Polygon'?'<outerBoundaryIs><LinearRing>':''}<coordinates>${cs}</coordinates>${f.geometry==='Polygon'?'</LinearRing></outerBoundaryIs>':''}</${f.geometry}></Placemark>`}});folders+=`<Folder><name>${xml(l.name)}</name>${body}</Folder>`});return`<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>${xml(project.name)}</name>${folders}</Document></kml>`}
 function dxfText(){const pair=(c,v)=>`${c}\n${String(v).replace(/[\r\n]+/g,' ')}\n`;let e='';exportFeatures().forEach(f=>{const l=layer(f.layerId),ln=(l.name||'0').replace(/[^A-Za-z0-9_-]/g,'_').slice(0,31),q=f.coords.map(toSLD);if(f.geometry==='Point')e+=pair(0,'POINT')+pair(8,ln)+pair(10,q[0][0].toFixed(3))+pair(20,q[0][1].toFixed(3))+pair(30,0);else{e+=pair(0,'POLYLINE')+pair(8,ln)+pair(66,1)+pair(70,f.geometry==='Polygon'?1:0);q.forEach(p=>e+=pair(0,'VERTEX')+pair(8,ln)+pair(10,p[0].toFixed(3))+pair(20,p[1].toFixed(3))+pair(30,0));e+=pair(0,'SEQEND')}if(f.properties?.name){const c=f.geometry==='Point'?q[0]:toSLD(centroid(f.coords));e+=pair(0,'TEXT')+pair(8,ln)+pair(10,c[0].toFixed(3))+pair(20,c[1].toFixed(3))+pair(30,0)+pair(40,2)+pair(1,f.properties.name)}});return pair(0,'SECTION')+pair(2,'HEADER')+pair(9,'$ACADVER')+pair(1,'AC1009')+pair(0,'ENDSEC')+pair(0,'SECTION')+pair(2,'ENTITIES')+e+pair(0,'ENDSEC')+pair(0,'EOF')}
 function csvText(){let s='Layer,Feature,Geometry,Point,Code,Remark,Latitude_WGS84,Longitude_WGS84,Easting_SLD99,Northing_SLD99,Accuracy_m\r\n';exportFeatures().forEach(f=>f.coords.forEach((p,i)=>{const en=toSLD(p),v=x=>'"'+String(x??'').replace(/"/g,'""')+'"';s+=[v(layer(f.layerId).name),v(f.properties?.name),v(f.geometry),i+1,v(f.properties?.code),v(f.properties?.remark),p[1].toFixed(7),p[0].toFixed(7),en[0].toFixed(3),en[1].toFixed(3),f.properties?.accuracy??''].join(',')+'\r\n'}));return s}
 const safeName=()=>project.name.replace(/[^\p{L}\p{N}_-]+/gu,'_');
 function backup(){saveNow();download(JSON.stringify(project,null,2),safeName()+'.fieldsketch.json','application/json')}
 $('projectBackupBtn').onclick=backup;$('exportKmlBtn').onclick=()=>download(kmlText(),safeName()+'.kml','application/vnd.google-earth.kml+xml');$('exportDxfBtn').onclick=()=>{try{download(dxfText(),safeName()+'_SLD99.dxf','application/dxf')}catch(e){toast(e.message)}};$('exportCsvBtn').onclick=()=>{try{download(csvText(),safeName()+'_coordinates.csv','text/csv')}catch(e){toast(e.message)}};
 $('shareBtn').onclick=async()=>{if(!project)return;const f=new File([JSON.stringify(project,null,2)],safeName()+'.fieldsketch.json',{type:'application/json'});if(navigator.canShare?.({files:[f]})){try{await navigator.share({title:project.name,text:'FieldSketch project backup',files:[f]})}catch(e){if(e.name!=='AbortError')toast('Share failed')}}else{backup();toast('Project downloaded; share it from Downloads')}};

 $('newProjectBtn').onclick=()=>$('projectModal').classList.add('show');$('openProjectBtn').onclick=openProjectDialog;$('projectChip').onclick=openProjectDialog;$('renameProjectBtn').onclick=()=>{if(!project)return;const n=prompt('Project name',project.name);if(n){project.name=n;autosave();renderAll()}};
 $('menuBtn').onclick=()=> $('mainMenu').classList.toggle('show');$('mainMenu').onclick=e=>{const a=e.target.dataset.act;$('mainMenu').classList.remove('show');if(a==='new-project')$('projectModal').classList.add('show');if(a==='open-project')openProjectDialog();if(a==='save-project'&&project)backup();if(a==='import-project')chooseFile('project','.json,.fieldsketch');if(a==='export-share')switchTab('projectPage')};
 $('addLayerBtn').disabled=false;
 ['A','R','P'].forEach(id=>$(id).oninput=()=>$('targetArea').textContent=arpText(targetM2()));
 function switchTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('on',x.dataset.tab===id));document.querySelectorAll('.tabpage').forEach(x=>x.classList.toggle('on',x.id===id));syncPanel()}
 $('tabs').onclick=e=>{const b=e.target.closest('.tab');if(b)switchTab(b.dataset.tab)};
 const panel=$('panel');function syncPanel(){const h=panel.classList.contains('collapsed')?38:Math.min(panel.offsetHeight,innerHeight*.44);document.documentElement.style.setProperty('--panelH',h+'px');setTimeout(()=>map.invalidateSize(),220)}function togglePanel(){panel.classList.toggle('collapsed');$('panelFab').firstChild.nodeValue=panel.classList.contains('collapsed')?'▴':'▾';syncPanel()}$('panelFab').onclick=togglePanel;$('grip').onclick=togglePanel;addEventListener('resize',syncPanel);new ResizeObserver(syncPanel).observe(panel);
 function closeModal(id){$(id).classList.remove('show')}
 const last=localStorage.getItem(ACTIVE_KEY);if(last&&projects[last])switchProject(last);else openProjectDialog();renderCodes();syncPanel();if(!window.proj4)setTimeout(()=>toast('SLD99 converter unavailable — check internet once'),700)
}
licenceGate();
