'use strict';
const $=id=>document.getElementById(id),PERCH_M2=25.29285264,ACRE=160,ROOD=40;
const PROJECTS_KEY='fieldsketch_projects_v3',ACTIVE_KEY='fieldsketch_active_v3',CODES_KEY='fieldsketch_codes_v3',LIC_KEY='fieldsketch_lic',LEGACY_LIC_KEY='rub'+'ber_lic';
const LIC_SECRET='RSK-bxNNco6NYy56aJ8n9L91D-9WOqVKNlp9-2026',TRIAL_DAYS=3;
const SLD99='+proj=tmerc +lat_0=7.00047152777778 +lon_0=80.7717130833333 +k=0.9999238418 +x_0=500000 +y_0=500000 +ellps=evrst30 +towgs84=-0.293,766.95,87.713,-0.195704,-1.695068,-3.473016,-0.039338 +units=m +no_defs +type=crs';
if(window.proj4)proj4.defs('EPSG:5235',SLD99);
const uid=p=>(p||'id')+'_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);
const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const xml=s=>String(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const arpToM2=(a,r,p)=>(a*ACRE+r*ROOD+p)*PERCH_M2;
function m2ToARP(m){let p=m/PERCH_M2,a=Math.floor(p/ACRE);p-=a*ACRE;let r=Math.floor(p/ROOD);p-=r*ROOD;return{a,r,p}}
function arpText(m){return SketchGeometry.arp(m)}
function ringArea(c){return c.length<3?0:SketchGeometry.area(c.map(toSLD))}
function lineLength(c){return SketchGeometry.length(c.map(toSLD))}
function distance(a,b){const r=6371008.8,p1=a[1]*Math.PI/180,p2=b[1]*Math.PI/180,dp=(b[1]-a[1])*Math.PI/180,dl=(b[0]-a[0])*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*r*Math.asin(Math.sqrt(h))}
function centroid(c){let x=0,y=0,z=0;c.forEach(p=>{const la=p[1]*Math.PI/180,lo=p[0]*Math.PI/180;x+=Math.cos(la)*Math.cos(lo);y+=Math.cos(la)*Math.sin(lo);z+=Math.sin(la)});return[Math.atan2(y,x)*180/Math.PI,Math.atan2(z,Math.hypot(x,y))*180/Math.PI]}
function toSLD(p){if(!window.proj4)throw Error('SLD99 converter unavailable');return proj4('EPSG:4326','EPSG:5235',p)}
// Refine the inverse against the forward operation: dropping ellipsoid height in
// a 2D datum conversion must not move an imported grid vertex on re-export.
function fromSLD(p){if(!window.proj4)throw Error('SLD99 converter unavailable');let c=proj4('EPSG:5235','EPSG:4326',p);for(let i=0;i<3;i++){const q=toSLD(c),ex=p[0]-q[0],ey=p[1]-q[1];if(Math.hypot(ex,ey)<.000001)return c;const step=.000001,x=toSLD([c[0]+step,c[1]]),y=toSLD([c[0],c[1]+step]),a=(x[0]-q[0])/step,b=(y[0]-q[0])/step,d=(x[1]-q[1])/step,e=(y[1]-q[1])/step,det=a*e-b*d;if(!Number.isFinite(det)||Math.abs(det)<1)throw Error('Coordinate is outside usable SLD99 coverage');c=[c[0]+(ex*e-ey*b)/det,c[1]+(ey*a-ex*d)/det]}if(SketchGeometry.dist(toSLD(c),p)>.001)throw Error('SLD99 coordinate conversion did not converge');return c}
function download(text,name,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),3000)}
let toastTimer;function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600)}

function b64u(buf){return btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64str(s){return decodeURIComponent(escape(atob(s.replace(/-/g,'+').replace(/_/g,'/'))))}
async function hmac(s){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(LIC_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64u(await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(s)))}
async function deviceId(){const s=[navigator.userAgent,navigator.platform,navigator.language,screen.width+'x'+screen.height,screen.colorDepth,Intl.DateTimeFormat().resolvedOptions().timeZone||''].join('|');return b64u(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).slice(0,16)}
const today=()=>new Date().toISOString().slice(0,10),dayDiff=(a,b)=>Math.floor((new Date(b+'T00:00:00Z')-new Date(a+'T00:00:00Z'))/86400000);
async function verifyKey(k){try{const[p,m]=k.trim().split('.');if(!p||!m||await hmac(p)!==m)return null;return JSON.parse(b64str(p))}catch(e){return null}}
async function licenceGate(){const modal=$('licenceModal'),msg=$('licenceMsg'),inputs=$('licenceInputs'),dev=await deviceId();$('deviceId').textContent=dev;modal.classList.add('show');const saved=localStorage.getItem(LIC_KEY)||localStorage.getItem(LEGACY_LIC_KEY);if(saved&&!localStorage.getItem(LIC_KEY))localStorage.setItem(LIC_KEY,saved);if(saved&&saved.includes('.')){const p=await verifyKey(saved);if(p&&(!p.d||p.d===dev)&&today()<=p.exp){modal.classList.remove('show');return boot()}}if(saved&&saved.startsWith('trial:')&&dayDiff(saved.slice(6),today())<TRIAL_DAYS){modal.classList.remove('show');return boot()}msg.textContent=saved?'Licence/trial expired or invalid. Enter a valid key.':'Enter a licence key or start the 3-day trial.';inputs.classList.remove('hidden');$('activateBtn').onclick=async()=>{const p=await verifyKey($('licenceKey').value);if(!p)return msg.textContent='Invalid licence key.';if(p.d&&p.d!==dev)return msg.textContent='This licence belongs to another device.';if(today()>p.exp)return msg.textContent='Licence expired on '+p.exp;localStorage.setItem(LIC_KEY,$('licenceKey').value.trim());modal.classList.remove('show');boot()};$('trialBtn').onclick=()=>{if(saved&&saved.startsWith('trial:'))return msg.textContent='Trial already used on this device.';localStorage.setItem(LIC_KEY,'trial:'+today());modal.classList.remove('show');boot()};$('copyDeviceBtn').onclick=async()=>{try{await navigator.clipboard.writeText(dev);toast('Device ID copied')}catch(e){toast('Copy unavailable')}}}


function boot(){
 if(!window.L||!window.proj4||!window.SketchGeometry){$('taskHint').textContent='Map components could not load. Connect to internet and reload; projects are unchanged.';return}
 const G=SketchGeometry,copy=x=>JSON.parse(JSON.stringify(x)),ll=c=>L.latLng(c[1],c[0]),coord=p=>[p.lng,p.lat],xy=c=>c.map(toSLD),now=()=>new Date().toISOString();
 const map=L.map('map',{zoomControl:false,doubleClickZoom:false,maxZoom:23}).setView([7.1731,80.3050],17);
 let baseLayer=null,baseGeneration=0;
 function setBasemap(choice,persist=true){const generation=++baseGeneration;if(baseLayer)map.removeLayer(baseLayer);const google=choice==='google',url=google?'https://mt{s}.google.com/vt?lyrs=s&x={x}&y={y}&z={z}':'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}';let failures=0,loaded=0;baseLayer=L.tileLayer(url,{subdomains:['0','1','2','3'],maxNativeZoom:google?20:19,maxZoom:23,attribution:google?'Basemap © Google Maps':'Imagery © Esri & contributors'}).on('tileload',()=>loaded++).on('tileerror',()=>{if(google&&generation===baseGeneration&&++failures>=4&&!loaded){setBasemap('esri',false);toast('Google XYZ unavailable. Showing Esri Satellite.')}}).addTo(map);$('basemapSelect').value=choice;$('basemapStatus').textContent=google?'Google Satellite · XYZ (unofficial)':'Esri Satellite';if(persist)localStorage.setItem('fieldsketch_basemap_v8',choice)}
 L.control.scale({imperial:false,position:'bottomleft'}).addTo(map);
 const savedGroup=L.layerGroup().addTo(map),draftGroup=L.layerGroup().addTo(map),ghostGroup=L.layerGroup().addTo(map),previewGroup=L.layerGroup().addTo(map),snapGroup=L.layerGroup().addTo(map),gpsGroup=L.layerGroup().addTo(map);
 let projects=readJSON(PROJECTS_KEY,{}),project=null,draft=null,selectedId='',editingId='',mode='draw',preview=null,cut=null,traceStart=null,history=[],future=[],snapCache=null,gpsWatch=null,epoch=0,saveTimer=null,joinIds=[],fileMode='',lastHover=0,snapEnabled=true,boundaryPicks=[],lastFix=null;
 const byId=id=>project?.features.find(f=>f.id===id),layer=id=>project?.layers.find(l=>l.id===id),locked=f=>!f||!!(f.locked||layer(f.layerId)?.locked);
 const snapNames={endpoint:'ENDPOINT / NODE',intersection:'INTERSECTION',nearest:'NEAREST',midpoint:'MIDPOINT',perpendicular:'PERPENDICULAR'};
 const geometry=m=>m==='polygon'?'Polygon':m==='point'?'Point':'LineString',methodFor=f=>f.geometry==='Polygon'?'polygon':f.geometry==='Point'?'point':f.coords.length===2?'line':'polyline';
 function readJSON(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')||f}catch{return f}}
 function guard(fn){try{const r=fn();if(r?.catch)r.catch(e=>toast(e.message));return r}catch(e){toast(e.message)}}
 function bind(id,fn){$(id).onclick=()=>guard(fn)}
 function hint(s,b){$('taskHint').textContent=s;if(b)$('modeBadge').textContent=b}
 function close(id){$(id).classList.remove('show')}
 function ensure(){if(project)return true;openProjects();return false}
 function target(){const a=+$('A').value,r=+$('R').value,p=+$('P').value;if(![a,r,p].every(Number.isFinite)||a<0||r<0||r>=4||p<0||p>=40||a%1||r%1)throw Error('Use whole acres / roods, 0–3 roods and 0–39.99 perches');return(a*160+r*40+p)*G.PERCH}
 function safeTarget(){try{return target()}catch{return 0}}
 function area(f){return Math.max(0,G.area(xy(f.coords))-(f.holes||[]).reduce((s,h)=>s+G.area(xy(h)),0))}
 function properties(){return{name:$('parcelNo').value.trim(),number:$('parcelNo').value.trim(),landName:$('landName').value.trim(),claimant:$('claimant').value.trim(),village:$('village').value.trim(),remark:$('remark').value.trim(),code:$('pointCode').value.trim()}}
 function fillProperties(p={}){for(const[id,k]of Object.entries({parcelNo:'name',landName:'landName',claimant:'claimant',village:'village',remark:'remark',pointCode:'code'}))$(id).value=p[k]||''}
 function defaultProject(name){return{schema:'fieldsketch-project',version:8,id:uid('project'),name,created:now(),updated:now(),layers:[['Parcels','parcel','#197568'],['Boundaries & Roads','line','#c58924'],['Streams & Drains','line','#287dc4'],['Survey Points','point','#cd5d49']].map(([name,kind,color])=>({id:uid('layer'),name,kind,color,visible:true,snap:true,export:true,locked:false,source:'survey'})),features:[],codes:readJSON(CODES_KEY,['BP','CP','ROAD','STREAM']),target:[0,0,0]}}
 function validateCoordinates(c,g){if(!Array.isArray(c)||(g==='Point'?c.length!==1:c.length<(g==='Polygon'?3:2))||c.some(p=>!Array.isArray(p)||!Number.isFinite(p[0])||!Number.isFinite(p[1])||Math.abs(p[0])>180||Math.abs(p[1])>90))throw Error('Invalid WGS84 coordinates or insufficient vertices')}
 function validateProject(p){if(p?.schema!=='fieldsketch-project'||!Array.isArray(p.features)||!Array.isArray(p.layers))throw Error('Not a FieldSketch project');const ids=new Set();for(const l of p.layers){if(!/^[A-Za-z0-9_-]+$/.test(l.id||'')||ids.has(l.id))throw Error('Duplicate / missing layer ID');ids.add(l.id);l.color=/^#[0-9a-f]{6}$/i.test(l.color||'')?l.color:'#287c6b';for(const k of ['visible','snap','export'])if(l[k]===undefined)l[k]=true}const fs=new Set();for(const f of p.features){if(!ids.has(f.layerId)||!/^[A-Za-z0-9_-]+$/.test(f.id||'')||fs.has(f.id)||!['Point','LineString','Polygon'].includes(f.geometry))throw Error('Invalid feature / layer reference');fs.add(f.id);validateCoordinates(f.coords,f.geometry);for(const h of f.holes||[])validateCoordinates(h,'Polygon');f.properties ||= {};delete f.vertexLocks}if(p.pendingDraft){const d=p.pendingDraft.draft;if(!d||!ids.has(d.layerId)||!['point','line','polyline','polygon'].includes(d.method)||d.geometry!==geometry(d.method)||!Array.isArray(d.coords))throw Error('Invalid unfinished sketch');for(const c of d.coords)validateCoordinates([c],'Point');d.properties ||= {};d.vertexMeta=d.coords.map((_,i)=>d.vertexMeta?.[i]||{source:'map'});if(p.pendingDraft.editingId&&!fs.has(p.pendingDraft.editingId))throw Error('Unfinished edit has no source feature')}return p}
 function save(immediate=false){if(!project)return;clearTimeout(saveTimer);const persist=()=>{if(!project)return;try{if(draft)draft.properties=properties();project.pendingDraft=draft?{draft:copy(draft),editingId}:null;project.autoReduce=$('autoReduce').checked;project.target=['A','R','P'].map(id=>$(id).value);project.updated=now();project.version=8;projects[project.id]=project;localStorage.setItem(PROJECTS_KEY,JSON.stringify(projects));localStorage.setItem(ACTIVE_KEY,project.id);$('saveStatus').textContent='Saved on device'}catch{$('saveStatus').textContent='SAVE FAILED';toast('Device storage unavailable / full. Export a project backup now.')}};if(immediate)persist();else{$('saveStatus').textContent='Saving…';saveTimer=setTimeout(persist,160)}}
 function snapshot(){if(draft)draft.properties=properties();return{features:copy(project.features),layers:copy(project.layers),draft:copy(draft),editingId,selectedId}}
 function checkpoint(){if(!project)return;history.push(snapshot());if(history.length>30)history.shift();future=[]}
 function invalidate(){snapCache=null}
 function stopWalk(){if(gpsWatch!==null){navigator.geolocation.clearWatch(gpsWatch);gpsWatch=null}$('walkStatus').textContent='Stopped · Save when ready'}
 function cancelTransient(){boundaryPicks=[];preview=null;cut=null;traceStart=null;joinIds=[];previewGroup.clearLayers();ghostGroup.clearLayers();snapGroup.clearLayers();$('previewPanel').classList.add('hidden');mode=draft?(editingId?'edit':'draw'):'select'}
 function restore(s){epoch++;stopWalk();project.features=s.features;project.layers=s.layers;draft=s.draft;editingId=s.editingId;selectedId=s.selectedId;cancelTransient();if(draft){$('method').value=draft.method;fillProperties(draft.properties)}invalidate();render();save()}
 function undo(){if(preview||mode.startsWith('split')||mode.startsWith('trace')){cancelTransient();hint('Operation cancelled. Parcel unchanged.');return}if(!history.length)return toast('Nothing to undo');future.push(snapshot());restore(history.pop());toast('Undone')}
 function redo(){if(!future.length)return toast('Nothing to redo');history.push(snapshot());restore(future.pop());toast('Redone')}
 function openProject(id){if(project)save(true);stopWalk();epoch++;cancelTransient();project=validateProject(projects[id]);selectedId='';draft=project.pendingDraft?.draft||null;editingId=project.pendingDraft?.editingId||'';history=[];future=[];['A','R','P'].forEach((k,i)=>$(k).value=project.target?.[i]||0);$('autoReduce').checked=project.autoReduce!==false;$('method').value=draft?.method||'polygon';$('method').dataset.prev=$('method').value;mode=editingId?'edit':'draw';fillProperties(draft?.properties||{});close('projectModal');invalidate();render();fitView();hint(draft?'Unfinished sketch restored. Continue picking or Save.':'Tap boundary points on the map. Polygon area updates live.','MAP PICK');save(true)}
 function openProjects(){$('projectChoices').innerHTML='';for(const p of Object.values(projects).sort((a,b)=>(b.updated||'').localeCompare(a.updated||''))){const el=document.createElement('button');el.className='choice';el.innerHTML='<b>'+esc(p.name)+'</b><span>'+p.features.length+' features · '+esc((p.updated||'').slice(0,10))+'</span>';el.onclick=()=>guard(()=>openProject(p.id));$('projectChoices').appendChild(el)}$('projectModal').classList.add('show')}
 function createProject(){const name=$('newProjectName').value.trim();if(!name)return toast('Enter a project name');const p=defaultProject(name);projects[p.id]=p;openProject(p.id);$('newProjectName').value=''}
 function fitView(c){const coords=c||project?.features.filter(f=>layer(f.layerId)?.visible).flatMap(f=>f.coords)||[];if(!coords.length)return;const desktop=innerWidth>=900;map.fitBounds(L.latLngBounds(coords.map(ll)),{paddingTopLeft:desktop?[430,170]:[35,165],paddingBottomRight:desktop?[85,85]:[70,Math.min(innerHeight*.42,350)+125],maxZoom:21,animate:false})}
 function shape(f,group,opts={}){if(f.type==='annotation')return L.marker(ll(f.coords[0]),{interactive:false,keyboard:false,icon:L.divIcon({className:'',html:'<span class="lot-label" style="color:'+esc(layer(f.layerId)?.color||'#fff')+'">'+esc(f.properties?.name)+'</span>',iconSize:[0,0]})}).addTo(group);const lat=f.geometry==='Polygon'?[f.coords.map(ll),...(f.holes||[]).map(h=>h.map(ll))]:f.coords.map(ll),base={color:layer(f.layerId)?.color||'#287c6b',weight:3,fillOpacity:.14,bubblingMouseEvents:false,...opts};return(f.geometry==='Point'?L.circleMarker(lat[0],{...base,radius:6,fillOpacity:1}):f.geometry==='Polygon'?L.polygon(lat,base):L.polyline(lat,base)).addTo(group)}
 function label(f,group){if(group===savedGroup&&f.labelVisible===false)return;if(f.geometry!=='Polygon'||f.coords.length<3)return;const p=G.labelPoint(xy(f.coords),(f.holes||[]).map(xy)),html='<div class="parcel-label"><b>'+esc(f.properties?.name||'Parcel')+'</b>'+(f.properties?.remark?'<small>'+esc(f.properties.remark)+'</small>':'')+'<strong>'+G.arp(area(f))+'</strong></div>';L.marker(ll(fromSLD(p)),{interactive:false,keyboard:false,icon:L.divIcon({className:'',html,iconSize:[0,0]})}).addTo(group)}
 function meta(f){if(f.type==='annotation')return 'Lot number · DXF text';return f.geometry==='Polygon'?G.arp(area(f))+' · '+area(f).toFixed(2)+' m²':f.geometry==='LineString'?G.length(xy(f.coords)).toFixed(2)+' m':'Point'}
 function renderMap(){savedGroup.clearLayers();if(!project)return;for(const f of project.features){if(!layer(f.layerId)?.visible||f.id===editingId)continue;const item=shape(f,savedGroup,{weight:f.id===selectedId||joinIds.includes(f.id)?5:3});item.on('click',e=>{if(mode==='select')select(f.id);else if(mode==='join')joinPick(f.id);else onMapClick(e.latlng)});label(f,savedGroup)}}
 function updateMeasure(candidate){const f=candidate||draft||byId(selectedId);if(!f){$('liveArea').textContent='0A 0R 0.00P';$('liveDetail').textContent='Tap map to start a parcel';$('targetDelta').textContent='Set target to subdivide';return}if(f.geometry==='Polygon'){const ar=area(f),t=safeTarget();$('liveArea').textContent=G.arp(ar);$('liveDetail').textContent=ar.toFixed(2)+' m² · '+(ar/10000).toFixed(4)+' ha · '+f.coords.length+' vertices';$('targetDelta').textContent=t?'Difference '+(ar-t>=0?'+':'')+((ar-t)/G.PERCH).toFixed(2)+'P':'Set target to subdivide'}else{$('liveArea').textContent=f.geometry==='Point'?'Point':G.length(xy(f.coords)).toFixed(2)+' m';$('liveDetail').textContent=f.coords.length+' vertices';$('targetDelta').textContent='Polygon required for subdivision'}$('measureTitle').textContent=(candidate?'CURSOR PREVIEW':draft?'LIVE EXTENT':'SELECTED FEATURE')+' · SLD99 grid'}
 function renderCoordinates(){const f=draft||byId(selectedId);$('coordTable').innerHTML=f?f.coords.map((p,i)=>{const q=toSLD(p);return'<tr><td>'+(i+1)+'</td><td>'+p[1].toFixed(7)+'</td><td>'+p[0].toFixed(7)+'</td><td>'+q[0].toFixed(3)+'</td><td>'+q[1].toFixed(3)+'</td><td>'+esc(String(f.vertexMeta?.[i]?.accuracy??'—'))+'</td></tr>'}).join(''):''}
 function renderDraft(){draftGroup.clearLayers();ghostGroup.clearLayers();if(draft){if(draft.coords.length>1)shape(draft,draftGroup,{interactive:false,color:'#dc9c2b',weight:3,fillOpacity:.13});label({...draft,properties:properties()},draftGroup);draft.coords.forEach((c,i)=>{if(mode==='edit'||mode==='deleteVertex'){const m=L.marker(ll(c),{draggable:mode==='edit',icon:L.divIcon({className:'',html:'<div class="vertex"></div>',iconSize:[20,20],iconAnchor:[10,10]})}).addTo(draftGroup);m.on('click',()=>{if(mode==='deleteVertex')deleteVertex(i)});m.on('dragstart',checkpoint);m.on('drag',e=>{draft.coords[i]=coord(e.target.getLatLng());ghostGroup.clearLayers();if(draft.coords.length>1)shape(draft,ghostGroup,{interactive:false,color:'#dc9c2b'});label({...draft,properties:properties()},ghostGroup);updateMeasure()});m.on('dragend',e=>guard(()=>{const hit=resolveSnap(e.target.getLatLng());draft.coords[i]=hit?hit.coordinate:coord(e.target.getLatLng());draft.vertexMeta[i]=hit?{source:'snap',kind:hit.kind,featureId:hit.featureId}:{source:'map'};draft.snapped ||=!!hit;invalidate();renderDraft();save()}))}else L.circleMarker(ll(c),{radius:5,color:'#fff',fillColor:'#c68720',fillOpacity:1,weight:2,interactive:false}).addTo(draftGroup)})}updateMeasure();renderCoordinates()}
 function renderLayers(){const selectedLayer=$('drawLayer').value,filter=$('featureFilter').value;$('layerList').innerHTML='';$('drawLayer').innerHTML='';$('editLayer').innerHTML='';$('featureFilter').innerHTML='<option value="all">All layers</option>';if(!project)return;for(const l of project.layers){const el=document.createElement('div');el.className='listitem';el.innerHTML='<div class="li-head"><span class="swatch" style="background:'+l.color+'"></span><span class="li-title">'+esc(l.name)+'</span></div><div class="li-meta">'+esc(l.source||'survey')+' · '+project.features.filter(f=>f.layerId===l.id).length+' features</div><div class="li-actions">'+[['visible','Show'],['snap','Snap'],['locked','Protect'],['export','Export']].map(([k,n])=>'<button class="'+(l[k]?'on':'')+'" data-layer="'+l.id+'" data-action="'+k+'" aria-pressed="'+!!l[k]+'">'+n+' '+(l[k]?'ON':'OFF')+'</button>').join('')+'<button data-layer="'+l.id+'" data-action="rename">Rename</button><button data-layer="'+l.id+'" data-action="zoom">Zoom</button></div>';$('layerList').appendChild(el);const option='<option value="'+l.id+'">'+esc(l.name)+'</option>';$('featureFilter').insertAdjacentHTML('beforeend',option);$('editLayer').insertAdjacentHTML('beforeend',option);if(!l.locked)$('drawLayer').insertAdjacentHTML('beforeend',option)}if(project.layers.some(l=>l.id===selectedLayer&&!l.locked))$('drawLayer').value=selectedLayer;else chooseDestination();if(project.layers.some(l=>l.id===filter))$('featureFilter').value=filter;renderFeatureList()}
 function renderFeatureList(){const filter=$('featureFilter').value;$('featureList').innerHTML=project?project.features.filter(f=>filter==='all'||f.layerId===filter).map(f=>'<div class="listitem '+(f.id===selectedId?'selected':'')+'"><div class="li-title">'+esc(f.properties?.name||f.type||'Feature')+'</div><div class="li-meta">'+esc(meta(f))+' · '+esc(layer(f.layerId)?.name)+(locked(f)?' · Protected':'')+'</div><div class="li-actions"><button data-feature="'+f.id+'" data-action="select">Select / zoom</button><button data-feature="'+f.id+'" data-action="details">Information</button></div></div>').join(''):''}
 function render(){if(!project)return;$('projectChip').textContent=project.name;renderMap();renderDraft();renderLayers();renderCodes();$('projectSummary').textContent=project.features.length+' features · '+project.layers.length+' layers · complete project autosave on this device';const f=byId(selectedId);$('selectionInfo').textContent=f?(f.properties.name||'Feature')+' · '+meta(f):'Select a feature on the map or in Layers.'}
 function chooseDestination(){if(!project)return;const kind=$('method').value==='polygon'?'parcel':$('method').value==='point'?'point':'line',l=project.layers.find(l=>l.kind===kind&&!l.locked);if(l)$('drawLayer').value=l.id}
 function select(id){if(draft?.coords.length&&editingId!==id)return toast('Save or cancel the unfinished sketch first');selectedId=id;mode='select';renderMap();renderFeatureList();updateMeasure();renderCoordinates();const f=byId(id),s=f?(f.properties.name||'Feature')+' · '+meta(f):'Tap an existing feature to select it.';hint(s,'SELECT');$('selectionInfo').textContent=s}
 function switchTab(id){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('on',b.dataset.tab===id));document.querySelectorAll('.tabpage').forEach(p=>p.classList.toggle('on',p.id===id));$('panel').classList.remove('collapsed');$('panel').scrollTop=0;syncPanel();if(id==='layersPage'&&!draft&&!preview)mode='select'}
 function syncPanel(){if(innerWidth<900)document.documentElement.style.setProperty('--panelH',($('panel').classList.contains('collapsed')?28:Math.min(innerHeight*.42,350))+'px');map.invalidateSize({pan:false})}
 function discardDraft(){if(draft?.coords.length&&!confirm('Discard unfinished sketch? Saved features stay unchanged.'))return false;draft=null;editingId='';epoch++;stopWalk();cancelTransient();invalidate();return true}
 function startNew(){if(!ensure())return;if(!discardDraft())return;checkpoint();selectedId='';fillProperties({});mode='draw';chooseDestination();render();save();hint('Tap map to add '+$('method').selectedOptions[0].text+' vertices.','MAP PICK')}
 function ensureDraft(){if(draft)return draft;const method=$('method').value,l=layer($('drawLayer').value);if(!l||l.locked)throw Error('Choose an editable destination layer in Advanced');const preferred=$('featureType').value,compatible=method==='polygon'?['parcel','building']:method==='point'?['point']:['boundary','road','footpath','stream','drain','fence','custom-line'];draft={method,geometry:geometry(method),type:compatible.includes(preferred)?preferred:compatible[0],coords:[],vertexMeta:[],layerId:l.id,properties:properties(),snapped:false};return draft}
 function addPosition(c,metadata={source:'map'}){if(!ensure())return;const d=ensureDraft();if(d.method==='line'&&d.coords.length>=2)return toast('Line already has two vertices. Save or choose Polyline.');if(d.method==='point'&&d.coords.length)return toast('Save this point before adding another.');if(d.coords.length&&G.dist(toSLD(d.coords.at(-1)),toSLD(c))<.001)return toast('This vertex is already present');if(d.geometry==='Polygon'&&d.coords.length>=3&&G.dist(toSLD(d.coords[0]),toSLD(c))<.005)return finish();checkpoint();d.coords.push(c.slice());d.vertexMeta.push(metadata);d.snapped ||=metadata.source==='snap'||metadata.source==='trace';invalidate();renderDraft();save();hint(d.coords.length+' vertices · tap to continue, Save to finish.','MAP PICK')}
 function finish(skipReduce=false){if(!draft?.coords.length)return toast('Tap map points first');const d=draft;if(d.geometry!=='Point'){const problem=G.validate(xy(d.coords),d.geometry==='Polygon');if(problem)return toast(problem)}if(d.method==='line'&&d.coords.length!==2)return toast('Line needs two vertices');if(editingId&&locked(byId(editingId)))return toast('Feature / layer is protected');const dest=layer(d.layerId);if(!dest||dest.locked)return toast('Destination layer is protected or missing');let reduced=null;if(!skipReduce&&d.geometry==='Polygon'&&$('autoReduce').checked&&target()>0&&area(d)>target()+.001)reduced=reduction(d,target());checkpoint();if(reduced){d.coords=reduced.coords;d.vertexMeta=reduced.vertexMeta}const props=properties();props.name ||=((d.geometry==='Polygon'?'Lot ':d.geometry==='Point'?'Point ':'Line ')+(project.features.length+1));props.number=props.name;const f={...copy(d),id:editingId||uid('feature'),properties:props,locked:false,created:byId(editingId)?.created||now(),updated:now()};delete f.method;if(editingId)project.features[project.features.findIndex(x=>x.id===editingId)]=f;else project.features.push(f);selectedId=f.id;draft=null;editingId='';epoch++;stopWalk();mode='select';invalidate();render();save(true);hint('Saved '+props.name+' · '+meta(f)+'. Subdivide or start a new sketch.','SAVED');toast(reduced?'Saved at target extent · shared boundary unchanged':'Joined '+f.geometry+' saved')}
 function snappingFeatures(screen=false){const out=[];if(!project)return out;for(const f of project.features){const l=layer(f.layerId);if(!l?.visible||!l.snap||f.id===editingId||f.type==='annotation')continue;[f.coords,...(f.holes||[])].forEach((c,ring)=>out.push({id:f.id,ring,closed:f.geometry==='Polygon',coords:c.map(p=>screen?screenPoint(ll(p)):toSLD(p))}))}return out}
 function screenPoint(p){const q=map.latLngToContainerPoint(p);return[q.x,q.y]}
 function resolveSnap(p,trace=false){if(!snapEnabled&&!trace)return null;if(!snapCache)snapCache=snappingFeatures(true);const sm=$('snapMode').value,modes=trace?['endpoint','nearest']:sm==='auto'?['endpoint','intersection','nearest']:[sm],anchor=draft?.coords.length?screenPoint(ll(draft.coords.at(-1))):null,candidates=mode==='draw'&&draft?.geometry==='Polygon'&&draft.coords.length>=3?snapCache.concat([{id:'__draftstart__',coords:[screenPoint(ll(draft.coords[0]))],closed:false}]):snapCache,hit=G.snap(screenPoint(p),candidates,{modes,radius:+$('snapRadius').value,anchor});if(!hit)return null;if(hit.featureId==='__draftstart__')return{...hit,coordinate:draft.coords[0].slice(),point:toSLD(draft.coords[0])};const f=byId(hit.featureId),c=hit.ring?f.holes[hit.ring-1]:f.coords;let coordinate;if(hit.kind==='endpoint')coordinate=c[hit.index].slice();else{const a=toSLD(c[hit.segment]),b=toSLD(c[(hit.segment+1)%c.length]);if(hit.kind==='intersection'){const o=byId(hit.other.featureId),oc=hit.other.ring?o.holes[hit.other.ring-1]:o.coords,h=G.intersection(a,b,toSLD(oc[hit.other.segment]),toSLD(oc[(hit.other.segment+1)%oc.length]));if(!h)return null;coordinate=fromSLD(h.point);hit.t=h.t}else{const h=hit.kind==='midpoint'?{point:G.lerp(a,b,.5),t:.5}:G.nearest(hit.kind==='perpendicular'?toSLD(draft.coords.at(-1)):toSLD(coord(p)),a,b);coordinate=fromSLD(h.point);hit.t=h.t}}return{...hit,coordinate,point:toSLD(coordinate)}}
 function showSnap(h){snapGroup.clearLayers();if(!h){$('snapStatus').textContent=snapEnabled?'OSNAP ready · '+$('snapMode').selectedOptions[0].text:'OSNAP OFF · free map points';return}const name=snapNames[h.kind];$('snapStatus').textContent=name+' · '+(h.featureId==='__draftstart__'?'Close parcel':byId(h.featureId)?.properties.name||'Reference');L.marker(ll(h.coordinate),{interactive:false,keyboard:false,icon:L.divIcon({className:'',html:'<div class="snap-marker '+h.kind+'">'+(h.kind==='intersection'?'×':'')+'</div>',iconSize:[22,22],iconAnchor:[11,11]})}).addTo(snapGroup).bindTooltip(name,{permanent:true,direction:'top',offset:[0,-12],className:'snap-tooltip'}).openTooltip()}
 function hover(p){if(!project||!['draw','edit','traceStart','traceEnd','insert'].includes(mode)||preview)return;const hit=resolveSnap(p,mode.startsWith('trace'));showSnap(hit);ghostGroup.clearLayers();if(mode==='draw'&&draft?.coords.length&&draft.geometry!=='Point'){const f={...draft,coords:draft.coords.concat([hit?hit.coordinate:coord(p)])};shape(f,ghostGroup,{interactive:false,color:'#bb9137',dashArray:'5,6',weight:2,fillOpacity:.035});updateMeasure(f)}}
 function pickFeature(p){const q=toSLD(coord(p));for(const f of [...project.features].reverse())if(layer(f.layerId)?.visible&&f.geometry==='Polygon'&&G.inside(q,xy(f.coords))&&!(f.holes||[]).some(h=>G.inside(q,xy(h))))return f;const candidates=project.features.filter(f=>layer(f.layerId)?.visible&&f.type!=='annotation').map(f=>({id:f.id,closed:f.geometry==='Polygon',coords:f.coords.map(c=>screenPoint(ll(c)))})),h=G.snap(screenPoint(p),candidates,{radius:28,modes:['endpoint','nearest']});return h?byId(h.featureId):null}
 function onMapClick(p){guard(()=>{if(!ensure()||(preview&&preview.kind!=='boundarySelection'))return;if(mode==='boundaryPick')return boundaryPick(p);if(mode==='select')return select(pickFeature(p)?.id||'');if(mode==='draw'){const hit=resolveSnap(p);showSnap(hit);return addPosition(hit?hit.coordinate:coord(p),hit?{source:'snap',kind:hit.kind,featureId:hit.featureId}:{source:'map'})}if(mode==='insert')return insertVertex(p);if(mode.startsWith('trace'))return traceClick(p);if(mode.startsWith('split'))return splitClick(p)})}
 function editGeometry(action='edit'){if(!ensure())return;if(!draft){const f=byId(selectedId);if(!f)return toast('Select a feature first');if(locked(f))return toast('Unlock feature / layer first');if(f.holes?.length)return toast('Editing polygons with holes is not supported; original retained');checkpoint();draft={...copy(f),method:methodFor(f),vertexMeta:copy(f.vertexMeta||f.coords.map(()=>({source:'map'})))};editingId=f.id;$('method').value=draft.method;fillProperties(f.properties)}mode=action;renderMap();renderDraft();switchTab('fieldPage');hint(action==='edit'?'Drag a vertex. Area updates during movement. Save changes.':action==='insert'?'Tap an edge to add a vertex.':'Tap a vertex to delete. Undo restores it.','EDIT')}
 function insertVertex(p){if(!draft||draft.geometry==='Point')return toast('Choose a line / polygon');const hit=G.snap(screenPoint(p),[{id:'draft',coords:draft.coords.map(c=>screenPoint(ll(c))),closed:draft.geometry==='Polygon'}],{modes:['nearest'],radius:30});if(!hit)return toast('Tap near an edge');if(hit.t<.001||hit.t>.999)return toast('Endpoint already exists here');checkpoint();const i=hit.segment,c=fromSLD(G.lerp(toSLD(draft.coords[i]),toSLD(draft.coords[(i+1)%draft.coords.length]),hit.t));draft.coords.splice(i+1,0,c);draft.vertexMeta.splice(i+1,0,{source:'insert'});invalidate();renderDraft();save();toast('Vertex added · Undo available')}
 function deleteVertex(i){if(!draft)return;checkpoint();draft.coords.splice(i,1);draft.vertexMeta.splice(i,1);invalidate();renderDraft();save()}
 function traceBegin(){if(!ensure())return;if(draft?.geometry==='Point'||$('method').value==='point')return toast('Choose Polygon or Polyline');if($('method').value==='line')return toast('Choose Polyline or Polygon to copy a boundary');ensureDraft();mode='traceStart';traceStart=null;switchTab('fieldPage');hint('Shared boundary 1/2: tap its START on a KML / DXF / saved edge.','TRACE')}
 function traceClick(p){const h=resolveSnap(p,true);showSnap(h);if(!h)return toast('Tap closer to a visible reference edge');if(byId(h.featureId).geometry==='Point')return toast('Choose a boundary, not a point');if(mode==='traceStart'){traceStart=h;mode='traceEnd';hint('Shared boundary 2/2: tap its END. All bends are copied.','TRACE');return}if(G.dist(traceStart.point,h.point)<.005)return toast('Choose a different end');const same=h.featureId===traceStart.featureId&&h.ring===traceStart.ring,f=byId(traceStart.featureId);preview={kind:'trace',start:traceStart,end:h,same,alternate:false,closed:f.geometry==='Polygon',coords:traceStart.ring?f.holes[traceStart.ring-1]:f.coords};try{tracePreview()}catch(e){preview=null;previewGroup.clearLayers();throw e}}
 function preserveCoordinate(p,source){for(const f of source?[source]:project.features)for(const ring of[f.coords,...(f.holes||[])])for(const c of ring)if(G.dist(toSLD(c),p)<.00001)return c.slice();return fromSLD(p)}
 function tracePreview(){const v=preview;v.route=v.same?G.traceRing(xy(v.coords),v.start,v.end,v.closed,v.alternate):G.traceNetwork(snappingFeatures(false),v.start,v.end);previewGroup.clearLayers();L.polyline(v.route.map(p=>ll(preserveCoordinate(p))),{color:'#e4a729',weight:6,interactive:false}).addTo(previewGroup);showPreview('Shared boundary preview',G.length(v.route).toFixed(2)+' m · '+v.route.length+' vertices. Source boundary stays unchanged.','Use boundary',v.same&&v.closed,false)}
 function acceptTrace(){const v=preview,d=ensureDraft(),route=v.route.map(p=>preserveCoordinate(p));if(d.coords.length&&G.dist(toSLD(d.coords.at(-1)),toSLD(route[0]))>.02&&!confirm('Trace starts away from the last vertex. Add a connecting line?'))return;checkpoint();for(const c of route)if(!d.coords.length||G.dist(toSLD(d.coords.at(-1)),toSLD(c))>.001){d.coords.push(c);d.vertexMeta.push({source:'trace',featureId:v.start.featureId})}if(d.geometry==='Polygon'&&d.coords.length>2&&G.dist(toSLD(d.coords[0]),toSLD(d.coords.at(-1)))<.001){d.coords.pop();d.vertexMeta.pop()}d.snapped=true;cancelTransient();mode='draw';invalidate();renderDraft();save();hint('Boundary copied. Continue tapping or Save.','MAP PICK')}
 function showPreview(title,text,accept,swap=false,split=false){$('previewTitle').textContent=title;$('previewText').textContent=text;$('acceptPreview').textContent=accept;$('swapPreviewBtn').classList.toggle('hidden',!swap);$('keepOther').classList.toggle('hidden',!split);$('keepBoth').classList.toggle('hidden',!split);$('previewPanel').classList.remove('hidden')}
 function splitOpen(){if(!ensure())return;if(draft){if(draft.geometry!=='Polygon')return toast('Draw / select a polygon');finish(true);if(draft)return}const f=byId(selectedId);if(!f||f.geometry!=='Polygon')return toast('Select a saved parcel');if(locked(f))return toast('Unlock parcel / layer');if(f.holes?.length)return toast('Subdivision of polygons with holes is not supported. Original retained.');const t=target();if(t<=0||t>=area(f))return toast('Required extent must be positive and smaller than this parcel');$('subdivisionInfo').textContent=(f.properties.name||'Parcel')+' · '+G.arp(area(f))+' → '+G.arp(t);$('subdivisionModal').classList.add('show')}
 function splitStart(kind){const f=byId(selectedId);cut={kind,sourceId:f.id,target:target(),picks:[],side:1};close('subdivisionModal');mode=kind==='parallel'?'splitLine':'splitVertex';switchTab('fieldPage');if(kind==='rotate'){previewGroup.clearLayers();for(const c of f.coords)L.circleMarker(ll(c),{radius:7,color:'#fff',weight:2,fillColor:'#cb922e',fillOpacity:1,interactive:false}).addTo(previewGroup)}hint(kind==='parallel'?'1/3: tap FIRST point of a line across the parcel.':'1/3: tap a highlighted parcel vertex.','SUBDIVIDE')}
 function drawCutGuide(){previewGroup.clearLayers();const[a,b]=cut.picks,d=G.dist(a,b),extent=Math.max(...xy(byId(cut.sourceId).coords).map(p=>G.dist(p,a)))*3,ux=(b[0]-a[0])/d,uy=(b[1]-a[1])/d;L.polyline([[a[0]-ux*extent,a[1]-uy*extent],[a[0]+ux*extent,a[1]+uy*extent]].map(p=>ll(fromSLD(p))),{color:'#d39427',weight:4,dashArray:'8,5',interactive:false}).addTo(previewGroup)}
 function splitClick(p){const f=byId(cut.sourceId),q=toSLD(coord(p));if(mode==='splitVertex'){const h=G.snap(screenPoint(p),[{id:f.id,coords:f.coords.map(c=>screenPoint(ll(c))),closed:true}],{modes:['endpoint'],radius:32});if(!h)return toast('Tap a highlighted vertex');cut.picks=[toSLD(f.coords[h.index])];mode='splitLine';hint('2/3: tap second point for line direction.','SUBDIVIDE');return}if(mode==='splitLine'){const h=resolveSnap(p);showSnap(h);const next=h?toSLD(h.coordinate):q;if(cut.picks.length&&G.dist(cut.picks[0],next)<.001)return toast('Choose a different point');cut.picks.push(next);if(cut.picks.length===1){hint('2/3: tap SECOND point across the parcel.','SUBDIVIDE');return}const[a,b]=cut.picks,c=xy(f.coords);if(G.area(G.clip(c,a,b,true))<.001||G.area(G.clip(c,a,b,false))<.001){cut.picks=cut.kind==='rotate'?[a]:[];return toast('Line must cross parcel interior. Pick its direction again.')}drawCutGuide();mode='splitSide';hint('3/3: tap INSIDE the side that needs the required extent.','PICK SIDE');return}if(mode==='splitSide'){if(!G.inside(q,xy(f.coords),false))return toast('Tap inside this parcel');const[a,b]=cut.picks;if(Math.abs(G.cross(a,b,q))/G.dist(a,b)<.03)return toast('Tap clearly on one side');cut.side=G.cross(a,b,q)>0?1:-1;calculatePreview()}}
 function calculatePreview(){const f=byId(cut.sourceId),r=G.split(xy(f.coords),...cut.picks,cut.target,cut.side,cut.kind);preview={kind:'split',...r,sourceId:f.id};previewGroup.clearLayers();const one={...f,coords:r.selected.map(p=>preserveCoordinate(p,f)),properties:{name:'Selected side',remark:''}},two={...f,coords:r.other.map(p=>preserveCoordinate(p,f)),properties:{name:'Other side',remark:''}};shape(one,previewGroup,{color:'#dc9c2b',fillOpacity:.32,interactive:false});shape(two,previewGroup,{color:'#7668c1',fillOpacity:.22,interactive:false});label(one,previewGroup);label(two,previewGroup);showPreview('Subdivision preview','Amber '+G.arp(G.area(r.selected))+' · Purple '+G.arp(G.area(r.other))+' · Difference '+(G.area(r.selected)-cut.target).toFixed(3)+' m²','Keep selected',true,true);hint('Check both parcels. Original changes only after Keep.','PREVIEW')}
 function acceptSplit(which){const v=preview,s=byId(v.sourceId);if(!s||locked(s))return toast('Source parcel protected / missing');checkpoint();const parts=which==='both'?[v.selected,v.other]:[which==='selected'?v.selected:v.other];project.features=project.features.filter(f=>f.id!==s.id);parts.forEach((c,i)=>{const name=which==='both'?(s.properties.name||'Lot')+'-'+(i+1):s.properties.name;const f={...copy(s),id:which==='both'?uid('feature'):s.id,coords:c.map(p=>preserveCoordinate(p,s)),holes:[],labelVisible:true,properties:{...s.properties,name,number:name,parentParcel:s.id},snapped:true,vertexMeta:c.map(()=>({source:'subdivision'})),updated:now()};project.features.push(f);selectedId=f.id});cancelTransient();mode='select';invalidate();render();save(true);hint('Subdivision saved. Undo restores the full original parcel.','SAVED');toast(which==='both'?'Both parcels kept':'Chosen parcel kept; other part removed. Undo can restore it.')}
 // Preserve recorded OSNAP/trace vertices even if their source is now hidden.
 function fixedVertices(f){const isReference=layer(f.layerId)?.source!=='survey',others=project.features.filter(o=>o.id!==f.id&&o.id!==editingId&&o.type!=='annotation');return f.coords.map((c,i)=>{if(isReference||f.vertexMeta?.[i]?.boundaryAnchor||['snap','trace'].includes(f.vertexMeta?.[i]?.source))return true;const p=toSLD(c);for(const o of others)for(const ring of[o.coords,...(o.holes||[])]){if(o.geometry==='Point'){if(G.dist(p,toSLD(ring[0]))<.001)return true;continue}const n=o.geometry==='Polygon'?ring.length:ring.length-1;for(let j=0;j<n;j++)if(G.nearest(p,toSLD(ring[j]),toSLD(ring[(j+1)%ring.length])).d<.001)return true}return false})}
 function reduction(f,t){if(f.holes?.length)throw Error('Auto-reduce with holes is not supported. Original retained.');const fixed=fixedVertices(f),result=G.reduceArea(xy(f.coords),t,fixed),coords=result.coords.map((p,i)=>fixed[i]||G.dist(p,toSLD(f.coords[i]))<.000001?f.coords[i].slice():fromSLD(p));if(Math.abs(G.area(xy(coords))-t)>.02)throw Error('Target-area check failed; original retained');return{coords,vertexMeta:coords.map((c,i)=>fixed[i]?{...(f.vertexMeta?.[i]||{source:'trace'}),boundaryAnchor:true}:{source:'auto-reduce'}),fixedCount:fixed.filter(Boolean).length}}
 function reducePreview(){if(!ensure())return;const f=draft||byId(selectedId);if(!f||f.geometry!=='Polygon')return toast('Draw or select a parcel');if(!draft&&locked(f))return toast('Unlock parcel / layer first');const t=target();if(t<=0||t>=area(f))return toast('Enter a smaller positive target extent');const result=reduction(f,t);preview={kind:'reduce',sourceId:draft?'':f.id,draft:!!draft,...result};previewGroup.clearLayers();shape({...f,coords:result.coords},previewGroup,{color:'#dc9c2b',interactive:false});label({...f,coords:result.coords},previewGroup);showPreview('Auto-reduce preview',G.arp(t)+' · '+result.fixedCount+' shared vertices unchanged','Apply reduction');hint('Only free vertices move. Check the outline, then Apply.','PREVIEW')}
 function acceptReduction(){const v=preview,f=v.draft?draft:byId(v.sourceId);if(!f||(!v.draft&&locked(f)))return toast('Parcel unavailable / protected');checkpoint();f.coords=copy(v.coords);f.vertexMeta=copy(v.vertexMeta);cancelTransient();invalidate();render();save(true);hint('Target extent applied. Shared boundary unchanged. Undo is available.')}
 function boundarySelectBegin(){if(!ensure())return;if($('method').value==='point'||$('method').value==='line')return toast('Choose Polygon or Polyline first');ensureDraft();boundaryPicks=[];mode='boundaryPick';preview={kind:'boundarySelection'};close('boundaryModal');showPreview('Select shared boundaries','Tap a saved line / polyline or polygon edge. Tap again to deselect.','Add to sketch');hint('Select adjoining boundaries in order, then Add to sketch.','BOUNDARY')}
 function boundaryPick(p){const h=G.snap(screenPoint(p),snappingFeatures(true),{modes:['nearest'],radius:+$('snapRadius').value});if(!h)return toast('Tap near a boundary line');const f=byId(h.featureId),ring=h.ring?f.holes[h.ring-1]:f.coords,whole=f.geometry==='LineString',key=f.id+':'+h.ring+':'+(whole?'all':h.segment),index=boundaryPicks.findIndex(x=>x.key===key);if(index>=0)boundaryPicks.splice(index,1);else boundaryPicks.push({key,featureId:f.id,coords:copy(whole?ring:[ring[h.segment],ring[(h.segment+1)%ring.length]])});previewGroup.clearLayers();for(const item of boundaryPicks)L.polyline(item.coords.map(ll),{color:'#ffdc35',weight:6,interactive:false}).addTo(previewGroup);$('previewText').textContent=boundaryPicks.length+' boundaries selected · tap again to deselect'}
 function acceptBoundaries(){if(!boundaryPicks.length)return toast('Select at least one boundary');const route=G.joinPaths(boundaryPicks.map(x=>xy(x.coords)));preview={kind:'trace',route,start:{featureId:boundaryPicks[0].featureId}};try{acceptTrace()}finally{if(preview)preview={kind:'boundarySelection'}}}
 function scalePreview(){if(draft)return toast('Save sketch first');const f=byId(selectedId);if(!f||f.geometry!=='Polygon'||locked(f))return toast('Select editable polygon');if(f.snapped||layer(f.layerId)?.source!=='survey'||f.holes?.length)return toast('Use Subdivide for imported / shared-boundary parcels');const t=target(),q=xy(f.coords);if(t<=0)throw Error('Enter target area');const c=G.labelPoint(q),k=Math.sqrt(t/G.area(q));preview={kind:'scale',sourceId:f.id,coords:q.map(p=>fromSLD([c[0]+(p[0]-c[0])*k,c[1]+(p[1]-c[1])*k]))};previewGroup.clearLayers();shape({...f,coords:preview.coords},previewGroup,{color:'#dc9c2b',interactive:false});showPreview('Free sketch scale preview','All vertices move. Target '+G.arp(t)+'. Shared boundaries excluded.','Accept scale')}
 function joinPick(id){const f=byId(id);if(f.geometry!=='LineString')return toast('Choose saved boundary lines');joinIds.includes(id)?joinIds.splice(joinIds.indexOf(id),1):joinIds.push(id);renderMap();$('joinStatus').textContent=joinIds.length+' lines selected in order'}
 function joinFinish(){if(!joinIds.length)return toast('Select boundary lines');let c=[];for(const [index,id] of joinIds.entries()){let part=copy(byId(id).coords);if(index===0&&joinIds.length>1){const next=byId(joinIds[1]).coords,ends=[toSLD(next[0]),toSLD(next.at(-1))],first=Math.min(...ends.map(p=>G.dist(p,toSLD(part[0])))),last=Math.min(...ends.map(p=>G.dist(p,toSLD(part.at(-1)))));if(first<last)part.reverse()}if(c.length){const last=toSLD(c.at(-1));if(G.dist(last,toSLD(part.at(-1)))<G.dist(last,toSLD(part[0])))part.reverse();if(G.dist(last,toSLD(part[0]))>.02)return toast('Selected boundaries have a gap. No connection was added.');part.shift()}c.push(...part)}const poly=$('joinOutput').value==='polygon';if(poly){if(G.dist(toSLD(c[0]),toSLD(c.at(-1)))>.02)return toast('Boundary is not closed. Select the closing line.');c.pop()}const err=G.validate(xy(c),poly);if(err)return toast(err);if(!discardDraft())return;checkpoint();$('method').value=poly?'polygon':'polyline';chooseDestination();draft={method:$('method').value,geometry:poly?'Polygon':'LineString',type:poly?'parcel':'boundary',coords:c,vertexMeta:c.map(()=>({source:'trace'})),snapped:true,layerId:$('drawLayer').value,properties:properties()};mode='draw';render();switchTab('fieldPage');save();hint('Joined boundary ready. Enter details and Save. Source lines retained.')}

 function updateGPS(){if(!lastFix){$('gpsAccuracy').textContent='GPS · no position yet';return}const age=Math.max(0,Math.floor((Date.now()-lastFix.timestamp)/1000));$('gpsAccuracy').textContent='GPS ±'+lastFix.accuracy.toFixed(1)+' m · '+(age>60?'last fix '+Math.floor(age/60)+' min ago':lastFix.recorded?'recorded':'last fix');$('gpsAccuracy').classList.toggle('stale',age>60);$('gpsAccuracy').title='Reported phone position accuracy; it is not parcel boundary accuracy.'}
 function gps(record=false,walk=false){if(!ensure())return;if(!navigator.geolocation)return toast('Location unavailable');if(!window.isSecureContext)return toast('Use the HTTPS GitHub Pages link for GPS');const job=project.id,requestEpoch=epoch,method=$('method').value;const success=p=>guard(()=>{if(!project||project.id!==job||epoch!==requestEpoch||$('method').value!==method)return;const c=[p.coords.longitude,p.coords.latitude],acc=p.coords.accuracy;if(!Number.isFinite(acc)||acc<0)return toast('GPS returned invalid accuracy');lastFix={accuracy:acc,timestamp:p.timestamp||Date.now(),recorded:false};updateGPS();gpsGroup.clearLayers();L.circle(ll(c),{radius:acc,color:'#287dc4',weight:1,fillOpacity:.12,interactive:false}).addTo(gpsGroup);L.circleMarker(ll(c),{radius:7,color:'#fff',fillColor:'#287dc4',weight:3,fillOpacity:1,interactive:false}).addTo(gpsGroup);if(!record){map.panTo(ll(c));return toast('Current position · ±'+acc.toFixed(1)+' m')}
   if(preview||mode.startsWith('split')||mode.startsWith('trace'))return toast('Finish current operation before GPS capture');const max=Math.max(1,+$('maxAccuracy').value||10);if(acc>max){if(walk){$('walkStatus').textContent='Skipped · ±'+acc.toFixed(1)+' m';return}if(!confirm('Phone GPS accuracy ±'+acc.toFixed(1)+' m. Record this approximate position?'))return}if(walk&&draft?.coords.length&&G.dist(toSLD(draft.coords.at(-1)),toSLD(c))<Math.max(.2,+$('walkDistance').value||2))return;const before=draft?.coords.length||0;addPosition(c,{source:'GPS',accuracy:+acc.toFixed(3),timestamp:new Date(p.timestamp).toISOString()});lastFix.recorded=(draft?.coords.length||0)>before;updateGPS();if(walk)$('walkStatus').textContent='Recording · '+(draft?.coords.length||0)+' vertices · ±'+acc.toFixed(1)+' m';else{mode='draw';map.panTo(ll(c));toast('GPS vertex recorded · ±'+acc.toFixed(1)+' m')}});
   const failure=e=>{toast('GPS: '+e.message);$('gpsAccuracy').textContent='GPS unavailable'+(lastFix?' · last ±'+lastFix.accuracy.toFixed(1)+' m':'')},options={enableHighAccuracy:true,maximumAge:0,timeout:20000};if(walk)gpsWatch=navigator.geolocation.watchPosition(success,failure,options);else navigator.geolocation.getCurrentPosition(success,failure,options);
 }
 function openAttributes(){const f=byId(selectedId);if(!f)return toast('Select a feature');for(const[id,k]of Object.entries({editName:'name',editLand:'landName',editClaimant:'claimant',editVillage:'village',editRemark:'remark'}))$(id).value=f.properties[k]||'';$('editLayer').value=f.layerId;$('editLock').checked=!!f.locked;$('editInfo').textContent=meta(f)+' · '+f.coords.length+' vertices';$('featureModal').classList.add('show')}
 function saveAttributes(){const f=byId(selectedId);if(!f)return;if(layer(f.layerId)?.locked)return toast('Unlock source layer first');const dest=layer($('editLayer').value);if(!dest||dest.locked)return toast('Destination layer protected');checkpoint();for(const[id,k]of Object.entries({editName:'name',editLand:'landName',editClaimant:'claimant',editVillage:'village',editRemark:'remark'}))f.properties[k]=$(id).value.trim();f.properties.number=f.properties.name;f.locked=$('editLock').checked;f.layerId=dest.id;close('featureModal');invalidate();render();save()}
 function renderCodes(){const codes=[...new Set([...readJSON(CODES_KEY,['BP','CP','ROAD','STREAM']),...(project?.codes||[])])];$('codeList').innerHTML=codes.map(c=>'<option value="'+esc(c)+'"></option>').join('');if(project)project.codes=codes}
 function newLayer(name,kind='reference',source='survey'){return{id:uid('layer'),name,kind,source,color:source==='survey'?'#287c6b':'#7266bd',visible:true,snap:true,locked:false,export:source==='survey'}}
 function parseKML(text,name){
   const doc=new DOMParser().parseFromString(text,'application/xml');if(doc.getElementsByTagName('parsererror').length)throw Error('Invalid KML XML');const out=[],desc=(el,n)=>Array.from(el.getElementsByTagNameNS('*',n)),direct=(el,n)=>Array.from(el.children||[]).find(e=>e.localName===n),content=(el,n)=>direct(el,n)?.textContent||'';
   const coordinates=el=>(desc(el,'coordinates')[0]?.textContent||'').trim().split(/\s+/).filter(Boolean).map(row=>{const p=row.split(',');return[Number(p[0]),Number(p[1])]});
   for(const pm of desc(doc,'Placemark')){const folders=[];for(let p=pm.parentElement;p;p=p.parentElement)if(p.localName==='Folder')folders.unshift(content(p,'name')||'Folder');const layerName=folders.join(' / ')||name.replace(/\.kml$/i,''),props={name:content(pm,'name'),remark:content(pm,'description')};for(const d of desc(pm,'Data')){const k=d.getAttribute('name');if(['name','number','remark','landName','claimant','village','code'].includes(k))props[k]=content(d,'value')}for(const geom of ['Polygon','LineString','Point'])for(const el of desc(pm,geom)){let c,holes=[];if(geom==='Polygon'){const outer=desc(el,'outerBoundaryIs')[0];if(!outer)continue;c=coordinates(outer);holes=desc(el,'innerBoundaryIs').map(coordinates)}else c=coordinates(el);const trim=c=>{if(c.length>1&&Math.abs(c[0][0]-c.at(-1)[0])<1e-10&&Math.abs(c[0][1]-c.at(-1)[1])<1e-10)c.pop();return c};if(geom==='Polygon'){trim(c);holes.forEach(trim)}validateCoordinates(c,geom);holes.forEach(h=>validateCoordinates(h,'Polygon'));out.push({geometry:geom,coords:c,holes,type:geom==='Point'&&props.code==='LOTNO'?'annotation':undefined,properties:{...props},layerName})}}
   if(!out.length)throw Error('No Polygon / LineString / Point features in KML');return{features:out,warnings:[]};
 }
 function parseDXF(text){
   if(text.startsWith('AutoCAD Binary DXF'))throw Error('Use ASCII DXF saved from CAD');const lines=text.replace(/\r/g,'').split('\n'),pairs=[];for(let i=0;i+1<lines.length;i+=2)pairs.push([lines[i].trim(),lines[i+1].trim()]);const records=[];let rec=null;for(const[code,value]of pairs){if(code==='0'){rec={type:value,tags:[]};records.push(rec)}else rec?.tags.push([code,value])}
   const tag=(r,n)=>r.tags.find(([c])=>c===String(n))?.[1],num=(r,n)=>{const v=tag(r,n);return v===undefined?NaN:Number(v)},out=[],warnings=new Map();let inEntities=false;const warn=t=>warnings.set(t,(warnings.get(t)||0)+1);
   function add(r,c,closed=false){if(c.some(p=>!p.every(Number.isFinite)))return warn(r.type+' invalid coordinate');if(c.some(p=>p[0]<100000||p[0]>1000000||p[1]<100000||p[1]>1200000))throw Error('DXF coordinates do not look like SLD99 metres. Convert to SLD99 first.');if(closed)c=G.clean(c);if(c.length<(closed?3:2)&&r.type!=='POINT')return warn('Too few vertices');out.push({geometry:r.type==='POINT'?'Point':closed?'Polygon':'LineString',coords:c.map(fromSLD),holes:[],properties:{name:'',remark:'Imported SLD99 DXF'},layerName:tag(r,8)||'0'})}
   for(let i=0;i<records.length;i++){const r=records[i];if(r.type==='SECTION'){inEntities=tag(r,2)==='ENTITIES';continue}if(r.type==='ENDSEC'){inEntities=false;continue}if(!inEntities)continue;if(['POLYLINE','LWPOLYLINE','LINE','POINT'].includes(r.type)&&(Math.abs(num(r,210)||0)>1e-12||Math.abs(num(r,220)||0)>1e-12||Number.isFinite(num(r,230))&&Math.abs(num(r,230)-1)>1e-12)){warn(r.type+' non-planar extrusion');if(r.type==='POLYLINE'){while(records[i+1]?.type==='VERTEX')i++;if(records[i+1]?.type==='SEQEND')i++}continue}
     if(r.type==='TEXT'||r.type==='MTEXT'){const lname=tag(r,8)||'0';if(!/(^|[|_])(LOTNO|TEXT[-_]LOT)$/i.test(lname))continue;let text=r.tags.filter(([k])=>k==='1'||k==='3').map(([,v])=>v).join('');text=text.replace(/\\U\+([0-9a-f]{4})/gi,(_,h)=>String.fromCharCode(parseInt(h,16))).replace(/%%[uUoOkK]/g,'').replace(/\\[ACFHQTWacfhqtw][^;]*;/g,'').replace(/\\S([^;]*);/g,'$1').replace(/\\P/g,' ').replace(/\\[LlOoKk]/g,'').replace(/\\~/g,' ').replace(/[{}]/g,'').trim();if(!text)continue;const aligned=r.type==='TEXT'&&((num(r,72)||0)!==0||(num(r,73)||0)!==0)&&Number.isFinite(num(r,11))&&Number.isFinite(num(r,21)),c=aligned?[num(r,11),num(r,21)]:[num(r,10),num(r,20)],before=out.length;add({...r,type:'POINT'},[c]);if(out.length>before)Object.assign(out.at(-1),{type:'annotation',textHeight:num(r,40)||1.8,textRotation:num(r,50)||0,properties:{name:text,remark:'',code:'LOTNO'}});continue}
     if(r.type==='LINE'){add(r,[[num(r,10),num(r,20)],[num(r,11),num(r,21)]]);continue}
     if(r.type==='POINT'){add(r,[[num(r,10),num(r,20)]]);continue}
     if(r.type==='LWPOLYLINE'){if(r.tags.some(([k,v])=>k==='42'&&Math.abs(+v)>1e-12)){warn('Curved polyline (bulge)');continue}let c=[],x;for(const[k,v]of r.tags){if(k==='10')x=Number(v);if(k==='20'&&x!==undefined){c.push([x,Number(v)]);x=undefined}}add(r,c,(num(r,70)&1)!==0);continue}
     if(r.type==='POLYLINE'){let c=[],curved=false;const flags=num(r,70)||0;if(flags&86)curved=true;while(i+1<records.length&&records[i+1].type==='VERTEX'){const v=records[++i];c.push([num(v,10),num(v,20)]);if(Math.abs(num(v,42)||0)>1e-12)curved=true}if(records[i+1]?.type==='SEQEND')i++;if(curved)warn('Curved / mesh polyline');else add(r,c,(flags&1)!==0);continue}
     if(!['SEQEND','VERTEX'].includes(r.type))warn(r.type);
   }
   if(!out.length)throw Error('No supported straight LINE / POLYLINE / POINT entities. '+[...warnings.keys()].join(', '));return{features:out,warnings:[...warnings].map(([t,n])=>n+' '+t+' skipped')};
 }
 function importColor(index){const palette=['#38bdf8','#f472b6','#facc15','#a3e635','#fb923c','#a78bfa','#2dd4bf','#fb7185'];if(index<palette.length)return palette[index];const h=(index*137.508)%360,s=.7,l=.6,a=s*Math.min(l,1-l),f=n=>{const k=(n+h/30)%12;return Math.round(255*(l-a*Math.max(-1,Math.min(k-3,9-k,1)))).toString(16).padStart(2,'0')};return'#'+f(0)+f(8)+f(4)}
 function importFeatures(result,filename,format){if(!result.features.length)return;checkpoint();const serial=project.importSerial??new Set(project.layers.filter(l=>l.source!=='survey').map(l=>l.importGroup||l.name.split(' / ')[0])).size,color=importColor(serial),group=uid('import');project.importSerial=serial+1;const layers=new Map();for(const item of result.features){if(!layers.has(item.layerName)){const l=newLayer(filename.replace(/\.(kml|dxf)$/i,'')+' / '+item.layerName,'reference',format);l.color=color;l.importGroup=group;l.fileName=filename;layers.set(item.layerName,l);project.layers.push(l)}const f={...item,id:uid('feature'),layerId:layers.get(item.layerName).id,type:item.type|| (item.geometry==='Polygon'?'parcel':item.geometry==='Point'?'point':'boundary'),locked:false,created:now(),snapped:true,labelVisible:format!=='DXF'||item.geometry==='Point'};delete f.layerName;f.properties.name ||=format+' '+(project.features.length+1);project.features.push(f)}invalidate();render();save(true);fitView(result.features.flatMap(f=>f.coords));switchTab('layersPage');toast(result.features.length+' features imported in '+layers.size+' layers'+(result.warnings.length?' · some entities skipped':''));if(result.warnings.length){const box=document.createElement('div');box.className='listitem';box.textContent='Import report: '+result.warnings.join('; ')+'. Convert required curves / blocks to straight polylines in CAD.';$('layerList').prepend(box)}}
 function chooseFile(kind){if(kind!=='project'&&!ensure())return;fileMode=kind;$('fileInput').accept=kind==='project'?'.json,.fieldsketch':kind==='kml'?'.kml':kind==='dxf'?'.dxf':'.kml,.dxf';$('fileInput').value='';$('fileInput').click()}
 async function importFile(){const file=$('fileInput').files[0];if(!file)return;const job=project?.id,kind=fileMode,text=await file.text();if(kind!=='project'&&project?.id!==job)return toast('Project changed; import cancelled');if(kind==='project'){const p=validateProject(JSON.parse(text));p.id=uid('project');p.name=(p.name||'Project')+' (Imported)';projects[p.id]=p;openProject(p.id);save(true);return toast('Complete project restored')}const format=kind==='kml'||/\.kml$/i.test(file.name)?'KML':'DXF',result=format==='KML'?parseKML(text,file.name):parseDXF(text);importFeatures(result,file.name,format)}
 function exportFeatures(){if(!ensure())return[];return project.features.filter(f=>layer(f.layerId)?.export)}
 function kmlText(){let folders='';const cs=c=>c.map(p=>p[0].toFixed(10)+','+p[1].toFixed(10)+',0').join(' '),ring=c=>cs(c.concat([c[0]]));for(const l of project.layers.filter(l=>l.export)){let body='';for(const f of project.features.filter(f=>f.layerId===l.id)){let geo;if(f.geometry==='Polygon')geo='<Polygon><outerBoundaryIs><LinearRing><coordinates>'+ring(f.coords)+'</coordinates></LinearRing></outerBoundaryIs>'+(f.holes||[]).map(h=>'<innerBoundaryIs><LinearRing><coordinates>'+ring(h)+'</coordinates></LinearRing></innerBoundaryIs>').join('')+'</Polygon>';else geo='<'+f.geometry+'><coordinates>'+cs(f.coords)+'</coordinates></'+f.geometry+'>';const c=l.color.replace('#',''),color=c.slice(4,6)+c.slice(2,4)+c.slice(0,2),props=Object.entries(f.properties||{}).map(([k,v])=>'<Data name="'+esc(k)+'"><value>'+xml(v)+'</value></Data>').join('');body+='<Placemark><name>'+xml(f.properties.name)+'</name><description>'+xml(f.properties.remark)+'</description><ExtendedData>'+props+'</ExtendedData><Style><LineStyle><color>ff'+color+'</color><width>3</width></LineStyle><PolyStyle><color>44'+color+'</color></PolyStyle>'+(f.type==='annotation'?'<IconStyle><scale>0</scale></IconStyle><LabelStyle><scale>0.7</scale></LabelStyle>':'')+'</Style>'+geo+'</Placemark>'}folders+='<Folder><name>'+xml(l.name)+'</name>'+body+'</Folder>'}return'<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>'+xml(project.name)+'</name>'+folders+'</Document></kml>'}
 function dxfText(){const pair=(c,v)=>c+'\n'+String(v).replace(/[\r\n]/g,' ')+'\n',unicode=s=>String(s||'').replace(/[^\x20-\x7e]/g,c=>'\\U+'+c.charCodeAt(0).toString(16).padStart(4,'0').toUpperCase()),names=new Map(project.layers.map((l,i)=>[l.id,('L'+(i+1)+'_'+l.name.replace(/[^A-Za-z0-9_-]/g,'_')).slice(0,60)]));let counter=256;const handle=()=>pair(5,(counter++).toString(16).toUpperCase());let body='',tables=pair(0,'TABLE')+pair(2,'LAYER')+pair(5,'1')+pair(330,'0')+pair(100,'AcDbSymbolTable')+pair(70,project.layers.length);for(const l of project.layers)tables+=pair(0,'LAYER')+handle()+pair(330,'1')+pair(100,'AcDbSymbolTableRecord')+pair(100,'AcDbLayerTableRecord')+pair(2,names.get(l.id))+pair(70,0)+pair(62,7)+pair(420,parseInt(l.color.slice(1),16))+pair(6,'CONTINUOUS');tables+=pair(0,'ENDTAB');
   function poly(c,closed,ln){const owner=counter.toString(16).toUpperCase();let s=pair(0,'POLYLINE')+handle()+pair(100,'AcDbEntity')+pair(8,ln)+pair(100,'AcDb2dPolyline')+pair(66,1)+pair(10,0)+pair(20,0)+pair(30,0)+pair(70,closed?1:0);for(const p of xy(c))s+=pair(0,'VERTEX')+handle()+pair(330,owner)+pair(100,'AcDbEntity')+pair(8,ln)+pair(100,'AcDbVertex')+pair(100,'AcDb2dVertex')+pair(10,p[0].toFixed(4))+pair(20,p[1].toFixed(4))+pair(30,0);return s+pair(0,'SEQEND')+handle()+pair(330,owner)+pair(100,'AcDbEntity')+pair(8,ln)}
   for(const f of exportFeatures()){const ln=names.get(f.layerId);if(f.type==='annotation'){}else if(f.geometry==='Point'){const p=toSLD(f.coords[0]);body+=pair(0,'POINT')+handle()+pair(100,'AcDbEntity')+pair(8,ln)+pair(100,'AcDbPoint')+pair(10,p[0].toFixed(4))+pair(20,p[1].toFixed(4))+pair(30,0)}else{body+=poly(f.coords,f.geometry==='Polygon',ln);for(const h of f.holes||[])body+=poly(h,true,ln)}if(f.properties?.name&&f.labelVisible!==false){const c=f.geometry==='Polygon'?G.labelPoint(xy(f.coords),(f.holes||[]).map(xy)):toSLD(f.coords[0]);for(const[i,t]of[f.properties.name,f.properties.remark,f.geometry==='Polygon'?G.arp(area(f)):''].filter(Boolean).entries())body+=pair(0,'TEXT')+handle()+pair(100,'AcDbEntity')+pair(8,ln)+pair(100,'AcDbText')+pair(10,c[0].toFixed(4))+pair(20,(c[1]-i*2.5).toFixed(4))+pair(30,0)+pair(40,f.type==='annotation'?(f.textHeight||1.8):1.8)+pair(50,f.type==='annotation'?(f.textRotation||0):0)+pair(1,unicode(t))+pair(100,'AcDbText')}}
   return pair(0,'SECTION')+pair(2,'HEADER')+pair(9,'$ACADVER')+pair(1,'AC1018')+pair(9,'$INSUNITS')+pair(70,6)+pair(0,'ENDSEC')+pair(0,'SECTION')+pair(2,'TABLES')+tables+pair(0,'ENDSEC')+pair(0,'SECTION')+pair(2,'ENTITIES')+body+pair(0,'ENDSEC')+pair(0,'EOF');
 }
 function csvText(){const quote=v=>{let s=String(v??'');if(/^[=+@-]/.test(s)&&!Number.isFinite(Number(s)))s="'"+s;return'"'+s.replace(/"/g,'""')+'"'},rows=[['Layer','Parcel','Land','Claimant','Village','Remarks','Code','Ring','Vertex','Latitude_WGS84','Longitude_WGS84','Easting_SLD99','Northing_SLD99','GPS_accuracy_m','Source','Area_m2']];for(const f of exportFeatures())[f.coords,...(f.holes||[])].forEach((ring,r)=>ring.forEach((p,i)=>{const q=toSLD(p);rows.push([layer(f.layerId).name,f.properties.name,f.properties.landName,f.properties.claimant,f.properties.village,f.properties.remark,f.properties.code,r,i+1,p[1].toFixed(7),p[0].toFixed(7),q[0].toFixed(3),q[1].toFixed(3),r===0?f.vertexMeta?.[i]?.accuracy:'',r===0?f.vertexMeta?.[i]?.source:'',f.geometry==='Polygon'?area(f).toFixed(3):''])}));return'\uFEFF'+rows.map(r=>r.map(quote).join(',')).join('\r\n')}
 const safeName=()=>project.name.replace(/[^\p{L}\p{N}_-]/gu,'_');
 function backup(){if(!ensure())return;save(true);download(JSON.stringify(project,null,2),safeName()+'.fieldsketch.json','application/json');toast('Project backup downloaded')}
 async function share(){if(!ensure())return;save(true);const file=new File([JSON.stringify(project,null,2)],safeName()+'.fieldsketch.json',{type:'application/json'});if(navigator.canShare?.({files:[file]})){try{await navigator.share({title:project.name,files:[file]})}catch(e){if(e.name!=='AbortError')toast('Share failed: '+e.message)}}else{backup();toast('Backup downloaded. Attach in WhatsApp / Gmail.')}}
 bind('projectChip',openProjects);bind('openProjectBtn',openProjects);bind('createProjectConfirm',createProject);bind('closeProjectModal',()=>{if(project)close('projectModal')});
 bind('renameProjectBtn',()=>{if(!ensure())return;const name=prompt('Project name',project.name);if(name?.trim()){project.name=name.trim();render();save()}});
 bind('newSketchBtn',startNew);bind('pickBtn',()=>{if(!ensure())return;if(preview)return toast('Accept / cancel preview first');mode='draw';renderDraft();switchTab('fieldPage');hint('Tap map points; snap markers show exact boundary positions.','MAP PICK')});
 bind('selectBtn',()=>{if(draft?.coords.length)return toast('Save or cancel the unfinished sketch first');cancelTransient();mode='select';renderDraft();hint('Tap saved parcel or line to select.','SELECT')});bind('finishBtn',()=>finish());bind('undoBtn',undo);bind('redoBtn',redo);bind('traceBtn',()=>{if(ensure())$('boundaryModal').classList.add('show')});bind('tracePortionBtn',()=>{close('boundaryModal');traceBegin()});bind('selectBoundaryBtn',boundarySelectBegin);bind('closeBoundaryModal',()=>close('boundaryModal'));bind('reduceBtn',reducePreview);
 bind('gpsBtn',()=>gps(true));bind('locateBtn',()=>gps(false));bind('fitViewBtn',()=>fitView());bind('zoomInBtn',()=>map.zoomIn());bind('zoomOutBtn',()=>map.zoomOut());bind('panelToggle',()=>{$('panel').classList.toggle('collapsed');syncPanel()});
 bind('editGeometryBtn',()=>editGeometry());bind('insertBtn',()=>editGeometry('insert'));bind('deleteVertexBtn',()=>editGeometry('deleteVertex'));bind('cancelEditBtn',()=>{if(discardDraft()){render();save();hint('Draft cancelled. Saved features unchanged.')}});bind('editAttributesBtn',openAttributes);
 bind('subdivideBtn',splitOpen);bind('parallelBtn',()=>splitStart('parallel'));bind('rotateBtn',()=>splitStart('rotate'));bind('closeSubdivision',()=>close('subdivisionModal'));bind('scaleBtn',scalePreview);
 bind('acceptPreview',()=>{if(!preview)return;if(preview.kind==='boundarySelection')return acceptBoundaries();if(preview.kind==='reduce')return acceptReduction();if(preview.kind==='trace')return acceptTrace();if(preview.kind==='split')return acceptSplit('selected');if(preview.kind==='scale'){const f=byId(preview.sourceId);checkpoint();f.coords=preview.coords;cancelTransient();invalidate();render();save()}});
 bind('keepOther',()=>acceptSplit('other'));bind('keepBoth',()=>acceptSplit('both'));bind('swapPreviewBtn',()=>{if(preview?.kind==='trace'){preview.alternate=!preview.alternate;tracePreview()}else if(preview?.kind==='split'){cut.side=-cut.side;try{calculatePreview()}catch(e){cut.side=-cut.side;throw e}}});
 bind('cancelPreview',()=>{cancelTransient();renderDraft();hint('Preview cancelled. Original geometry unchanged.')});
 bind('snapToggle',()=>{snapEnabled=!snapEnabled;$('snapToggle').textContent='OSNAP '+(snapEnabled?'ON':'OFF');$('snapToggle').classList.toggle('on',snapEnabled);$('snapToggle').setAttribute('aria-pressed',snapEnabled);showSnap(null)});
 bind('joinStartBtn',()=>{if(!ensure())return;if(draft?.coords.length)return toast('Save / cancel sketch first');joinIds=[];mode='join';hint('Tap required saved lines in joining order.','JOIN');$('joinStatus').textContent='Tap required lines on map'});bind('joinFinishBtn',joinFinish);
 bind('walkStartBtn',()=>{if(gpsWatch!==null)return;if($('method').value!=='polygon')return toast('Select Polygon before boundary walk');gps(true,true);$('walkStatus').textContent='Waiting for GPS…'});bind('walkStopBtn',stopWalk);
 bind('saveAttributes',saveAttributes);bind('closeFeature',()=>close('featureModal'));bind('deleteFeature',()=>{const f=byId(selectedId);if(!f||locked(f))return toast('Unlock feature / layer first');if(!confirm('Delete feature? Undo can restore it.'))return;checkpoint();project.features=project.features.filter(x=>x.id!==f.id);selectedId='';close('featureModal');invalidate();render();save()});
 bind('addCodeBtn',()=>{const code=prompt('New code',$('pointCode').value);if(!code?.trim())return;localStorage.setItem(CODES_KEY,JSON.stringify([...new Set([...readJSON(CODES_KEY,[]),code.trim()])]));$('pointCode').value=code.trim();renderCodes();save()});
 bind('addLayerBtn',()=>{if(!ensure())return;const name=prompt('New layer name','Additional features');if(!name?.trim())return;checkpoint();const l=newLayer(name.trim(),'line');project.layers.push(l);renderLayers();$('drawLayer').value=l.id;save()});
 bind('fieldImportBtn',()=>chooseFile('reference'));bind('importKmlBtn',()=>chooseFile('kml'));bind('importDxfBtn',()=>chooseFile('dxf'));bind('importProjectBtn',()=>chooseFile('project'));$('fileInput').onchange=()=>guard(importFile);
 bind('backupBtn',backup);bind('shareBtn',share);bind('exportKmlBtn',()=>{if(ensure())download(kmlText(),safeName()+'.kml','application/vnd.google-earth.kml+xml')});bind('exportDxfBtn',()=>{if(ensure())download(dxfText(),safeName()+'_SLD99.dxf','application/dxf')});bind('exportCsvBtn',()=>{if(ensure())download(csvText(),safeName()+'_coordinates.csv','text/csv')});
 $('layerList').onclick=e=>guard(()=>{const b=e.target.closest('[data-layer]');if(!b)return;const l=layer(b.dataset.layer),action=b.dataset.action;if(action==='zoom')return fitView(project.features.filter(f=>f.layerId===l.id).flatMap(f=>f.coords));checkpoint();if(action==='rename'){const n=prompt('Layer name',l.name);if(n?.trim())l.name=n.trim()}else l[action]=!l[action];invalidate();render();save()});
 $('featureList').onclick=e=>guard(()=>{const b=e.target.closest('[data-feature]');if(!b)return;select(b.dataset.feature);const f=byId(b.dataset.feature);if(b.dataset.action==='details')openAttributes();else{fitView(f.coords);switchTab('fieldPage')}});
 $('featureFilter').onchange=renderFeatureList;$('method').dataset.prev=$('method').value;
 $('method').onchange=()=>guard(()=>{const next=$('method').value;if(draft?.coords.length&&!confirm('Start new '+next+'? Unfinished sketch will be discarded.')){$('method').value=$('method').dataset.prev;return}if(project)checkpoint();draft=null;editingId='';epoch++;stopWalk();cancelTransient();mode='draw';$('method').dataset.prev=next;chooseDestination();invalidate();render();save();hint('Tap map to add '+next+' vertices.','MAP PICK')});
 $('featureType').onchange=()=>{const type=$('featureType').value,expected=['parcel','building'].includes(type)?'Polygon':type==='point'?'Point':'LineString';if(draft&&draft.geometry!==expected)return toast('Change Geometry in Field first');if(draft){draft.type=type;save()}};
 $('drawLayer').onchange=()=>{if(draft){draft.layerId=$('drawLayer').value;save()}};
 for(const id of ['parcelNo','landName','claimant','village','remark','pointCode'])$(id).addEventListener('input',()=>{if(draft){draft.properties=properties();renderDraft()}save()});
 for(const id of ['A','R','P'])$(id).addEventListener('input',()=>{updateMeasure();save()});
 $('snapMode').onchange=()=>showSnap(null);$('snapRadius').onchange=()=>showSnap(null);
 $('tabs').onclick=e=>{const t=e.target.closest('[data-tab]');if(t)switchTab(t.dataset.tab)};
 $('autoReduce').onchange=()=>save();$('basemapSelect').onchange=()=>setBasemap($('basemapSelect').value);
 map.on('click',e=>onMapClick(e.latlng));map.on('mousemove',e=>{if(Date.now()-lastHover>45){lastHover=Date.now();guard(()=>hover(e.latlng))}});map.on('mouseout',()=>{ghostGroup.clearLayers();updateMeasure()});map.on('moveend zoomend',()=>{invalidate();snapGroup.clearLayers()});
 addEventListener('resize',syncPanel);addEventListener('pagehide',()=>save(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)save(true)});
 addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key==='Escape'){cancelTransient();renderDraft()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}});
 function migrate(){if(Object.keys(projects).length)return;for(const j of Object.values(readJSON('fieldsketch_jobs_v2',{}))){const p=defaultProject(j.name||'Previous job');for(const[i,f]of(j.saved||[]).entries()){const c=(f.pts||[]).map(v=>[v[1],v[0]]);if(c.length>=3)p.features.push({id:uid('feature'),layerId:p.layers[0].id,geometry:'Polygon',type:'parcel',coords:c,properties:{name:f.sb||'Lot '+(i+1),remark:f.remark||''},locked:false})}if(j.refs?.length){const l=newLayer('Previous references','reference','KML');p.layers.push(l);for(const c of j.refs){const coords=c.map(v=>[v[1],v[0]]);if(coords.length>=2)p.features.push({id:uid('feature'),layerId:l.id,geometry:coords.length>=3?'Polygon':'LineString',type:'boundary',coords,properties:{name:'Previous reference'},locked:false})}}projects[p.id]=p}}
 setBasemap(localStorage.getItem('fieldsketch_basemap_v8')||'google',false);setInterval(updateGPS,15000);
 migrate();const last=localStorage.getItem(ACTIVE_KEY);if(last&&projects[last])guard(()=>openProject(last));else openProjects();renderCodes();syncPanel();
 if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{$('offlineStatus').textContent='Offline app cache unavailable. Keep internet on; save project backups.'});
}
licenceGate().catch(e=>{$('taskHint').textContent='Startup error: '+e.message;toast(e.message)});
